secretData:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:uVnBDcP0olGe8lGyYMz4Bh4H33XWhKV+ju2Kc0TLbNX+czDSOPwuthH4tEqxgUBa,iv:tlK6zGul9EaUNITa3bn02vJ6Rbxod272vAtVJXe2Z3A=,tag:cvAKH4fRuaWRjx7lNwWuGQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:S0+Dwb4cLvao9cCo/gqhvo5aTOZAjyyTaFRxSskn8pDoc4hGbuEoTS3zgM/SHQ+lwcwIb5vlqPQhsDQkZSM2k4VSfVl0Hrn2Ih1MwSgT+piljgCbB3aXfrhVSMvwm0Wn,iv:0iMP8o8kRwy7oypMxELfO8Gd/kWH4hFB7taVprmyoUc=,tag:1HN6K7BdJHaV15z2TEanRA==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:Rqy4ClTzK5b79XeXhvwTN/6AGqlhdONYKySsbQ==,iv:GUmKZXjY4KJCGD6vwbf097vmuCdYbprPsIqUJABoA1Q=,tag:gsrq9dOPiRnMLpQJo1uYFw==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:jV1Pa87Tfig+JyEwUwx5JaDqTg63g07JjYwFRh+zrtv1KT/YsJqZ1ZmeIl678y24PiLZ4vLhRQI=,iv:VQi//cbm31KiA0McvQt7UQk7HXnbkOA2nWKfCY8jwM0=,tag:0wPeDw9b9UCQsD7oNBKgxg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:UWCPYn+ZcwsPE+n7qYvO1w==,iv:dDvGkwKyrWfK5kVdKDjArYc2RB6kIogxfZrqU4RmJ/w=,tag:LOSsTkr8VbyQRTeV3kUkRA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:oJZUZxNn+IyPIR+/SGC17rKqDBHvG80MRYUA8LPzQRJE2mgh15Zu2bUWEMfKL5F65epbZSj1VaH/4CADdyT0Qw==,iv:cbZ9fywY7EAhTJo5BRyhXX3v3YiWmOkyF9gN+iUJP4o=,tag:aSZs/51HtN9vQQosnj4DRg==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:cMtu8jb6PMbiD1KB7TYCQwU11p29l0Nucd8LSVIu9lqvOZ0VY+H3y9ZGWZFxtBmH11zKCVDWlNokonZYmHW3TtplwXD4Jbm/4OloG05LH2gLTC5qekh1Gi8OtrB0KxwqucX0WjdvWn0OPzcu,iv:ROOF9eFFZJB71j4M1Ni7onK4ouRAnHWqVbUlJ9ohWp4=,tag:0RLOy0cpeqPJz2WSkyNzzA==,type:str]
imagePullSecrets:
    enabled: ENC[AES256_GCM,data:bY8Vww==,iv:mOIwZbNrn2c5wK+8NRKx4vnAPyAPdnSa87+uQQwV6pw=,tag:Hx7g75qSbSVgwFpAVy5q4Q==,type:bool]
    name: ENC[AES256_GCM,data:2+N9C6XXMq3SeXMvS04=,iv:Mvau1sYGP5KIupB3EPHcuHRejwtjMIrvPcSa7iFiY8Y=,tag:dF5aB9TvSVuVIk952rlGBw==,type:str]
    registry: ENC[AES256_GCM,data:oA7k/NNjbEhZxH8u99uln9xiLIbTszi7oTOm,iv:sQO+6Lc73zuucwTDHXW5PGXhZBTYZnxe74FMIVaS+Vw=,tag:lCJkEvmWSGLke77MbFUUFA==,type:str]
    username: ENC[AES256_GCM,data:zRu2C88pzdmjTTM=,iv:9ZzH7JtMRFolJIB3eHu/zqNiDckg/vcVoKr80vJk15M=,tag:tjp36wsiEkFX7sdNyWhpCg==,type:str]
    password: ENC[AES256_GCM,data:Lgpg1HG2Fa3GlmI=,iv:1qmv+JhI4m1ud0HJCM/yVTKDoH9pkeoWM268LNKNCGQ=,tag:6Kivbz/yBAME8TPM/ed6TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cVlQNUxVUFVWUk8wdlpS
            TkJoUG10VnRPL0ZkUTRFRExwQVVQMVczVUVBCmRXakhZRGdTU2cwVXdWeXZERTZ6
            OFB2VGxDS2Z6TFZGN1B5VTJtc1loazQKLS0tIHZ1Ukh3enJnK091WDdxeHhRRjlU
            bzRFSTFGN3dMUTRrR3o0UXo4YUhwODQKRUJcWrhrl2TG2xwCLF5WK3MCMUxJao/r
            4iEe7pOgWETKpf/42HIph7qSMcFicyJGc/+zKSZtFIbo2RZFCpm6YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:05:19Z"
    mac: ENC[AES256_GCM,data:165JAFQfed2KZD8VMsUIioDCupPd7/F8oIIvPDesKpDEltPvQhg2p+61HMIYh3gS8KaATgYE0xuYAgSyiCT5gamxEXhC0WKhBa2Tt2Lr3tbTnzBuGIjWGCqiOAwtO2u3x2Dv/TQKBtbrgPQzkaac15GXW+jjkkaYAsw9jggTKc0=,iv:6UAEQZyMT5PPBW8Am45+uM5sE/cQJ+EEmHpuRth3n6c=,tag:eT9zpkb20A38NHC+g8zEVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
