secretData:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:zheii1WEPXzVyk0swCK1aNC8EZvMNAmDUyiR9IWPYU1lpoc=,iv:KDx2frHu09TDlEKudN+LOTlgbuaOwEIv6TCh5MQmfXI=,tag:Uo0abuMSjuHJT0UCcVInWA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:1n3Wn7bwpxG1uTtESac+vumH3eVlF43cJ1LbxFjduiJfSoHaQpzVYZWWZESIuUc0uqu4olOIaaJmJBpwy9KFxg55W1MRwbqW,iv:kvR4mV2/MIqzzc6EPU1G6wi3i+iaf6SEILIdaYV9VOo=,tag:3ZeaasECv3raE6Pcna/fOQ==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:OI+/3vevVjIE5+kJfhRylisXlGY=,iv:gryTCLD6n4d+h2o5c6VLWsiBIZFVHBy99iwOrEU4LBE=,tag:4bpfqsB6ePtrGLTEacm9mA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:bSQb6Gh71JJMcmin1yOfpT4YsN1cuaS1l2SNN7Z/jGCTeSxU+aOJVQ==,iv:E38b/BfJKLgLrSYp5VCAqKPNgbPwAMHtlIGdDdqRuf0=,tag:jqguwI5m5prJ1yN2HeucRw==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:noRE,iv:NlBVHUkDke0Ko/cB9YVRV8VTFVcKi74qjoaCK786/LY=,tag:O1TV5YVBct9w+oaCaW0PgQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tqo4OJcNXHtvmjdt3odbYSkXvwQI/KCtfdaf7i099iYb+9k7rYlAIgE6T59SUQ==,iv:uXFJq9++uJPfrLV9cbbznkeZo1dVT0DtO0sbA+bhLMI=,tag:di8VRCNs2PkwnTpx/mMUpg==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:CACi1twfxpIKv0d3qvlzlTbrzNo+SKBvhs0enmg4W81QWXvhM8LlIkvtA/OtM4uqsVZ7yLPFYcU6kLg9FtUKVOAkHLEDgEsdbjUFPXTllTk=,iv:OOwJGcTzFtpn75K+zQTFz8ZjezgXXLkDFC+CQUx8HoY=,tag:/+5H22rubJdGOYwGblCPCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YTZ6MGw1L0JjcGZlSE1l
            eGpmbVdmelNvZW95OXZIWnVtZTRJQXYyaFE0CllrK3JqVStIc05VQmVvVW9lYldJ
            VGZOSCttdFZWSGdEdmN0R2hqRkxOWFEKLS0tIC80UkpVZzhYcVpidGtsS1lhM1FZ
            b01Bb2dmS2RvU0NXb0R2UzdhV0FDbEkKAmLHERmFZOgsORDDdGIdRrieLe2NlZ7k
            +3r+Vai5QFWb4rc8rsu9md09znhbDcfl0KcStiML6QL6zRfd6XEU2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T02:29:58Z"
    mac: ENC[AES256_GCM,data:gOVB4DyYK65/cz+ne7IhNkM9bCkHbRRlBdLFEwDl+6oXKpMzQuy35JAnBxhPp/r7X250pMzmFjj09/nzamef/8+omQOgZnuPE4rfMSUMrKIIvk6CwVyigMV1HgIlRaREOnDueuaZza8KeOlPLkq6l5MTKxr50t+wHx8X/jcysaI=,iv:oRePKALBYPGyAND+gAIBk/oQlXzg9DFW4f+qI2BrZ8o=,tag:IIbr9lH1Abs2vlHcRwXtew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
