secretData:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:34vkSLoxVIfE6QEGaFYNUYjsr7KUkz8YE55EVjl05D2b0eo=,iv:eTK/7K2oIa+1Qhb48UbXP1Q107BboykrtadTPqaAYc4=,tag:fJbboUS8ArtQ8DLugP2TWg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:14tP+qpOyCUwsPrl2ZIpf+btDfvXHx5vcuqPFXQcPlebTEACAQeclhb6ZsVAIpEMBipSd8i6/SflHgIOE+3oShtOL/G1OZBA,iv:ZzFp6txmWcgm0W3kOYjvmkcUU+L+sWhtTc1gKPL76EE=,tag:jRhdNI4AzjPd8H9BsB9MEw==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:E7zUonWeeN3pGD0sH+ACneebptU=,iv:05jBE/mVw2ya9msJYzNrg4WaAXFYM7Oz4Jz6hXcYljI=,tag:sMS69JO7LcY/phJ+D5udGQ==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:8Sdd4g0diYmly6VwZzd7Ce3iIuQ690XQOf+qPBex6hvQ+garjzB1wQ==,iv:TagU3icg21VEbhZjKaKDU/Kjkt81aGrNxb7Tv2EEfpw=,tag:Z/GLHwCXs2wkjBM+H9b+zA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:frxiYvhXOLHLolCt,iv:NqJT0R4Iv6R2izjF0bUuFPm6snUWZgJfza6VheWkitM=,tag:1r/nmCfYV4AqOSQTgqvh+Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:DGw+hhX9P2bwezvR+5JqEKQwd+WAHFfLw5tqNhVie3D+JagYr0npS/1+UtOhgg==,iv:mKigfj0WruydVPWMiGpdZL6rTW7JLBT3gdwgDSoFrSk=,tag:KY4DzSnsOKNPiFKnOd7XzQ==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:VAHSC46qawwXFldnRscpnVWDs4YEfk0HNJ+MQr84Wpca7/UHMFpecZytigjxqQcH01fAsgLloQy7xdVNwLs72YN7IoRd+Ze2Dfx7MYuEM54=,iv:Gd6Yrs0NLF83+vTX6HS9UjMuXln6WQZqTuoaI2+DgDs=,tag:dcsXPv4oBmVAX8YVBSzPjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdS9jdG0va2pUNDdSd3Iw
            eWh5ZTBMNHBWQVkycDZlRVk3L0dRcTVONUZnCjNmVHNEaGo4dE15aWJZWnpabE4z
            MFA2dk41ZjlOMHBWQkUvTkl0bE9JUG8KLS0tICtma01jQ29VbitWaFpKcnRxS2Rj
            TE5LWmtnT1JyZkpiWm8yQ3pPQ2taRkkKbx/3RbX93e9D9UXEVRW0ccLIvsZyns27
            b76PcovmG78q5AIXi5yF1DWl6A6QbdIRNqxgNSvhOq/LsU9stAtN7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T22:25:50Z"
    mac: ENC[AES256_GCM,data:Y2WH5Zpw2V8IfomqmsKiKMuBRicDgPgOvf9P2LVLVYPC9PrgUOtSQ8Yu9KRPaX/6MGAaXWayuXdhHVLwJgVZtlnLA2bmevXqoynbwLfS1DnSvL5aoArQPU42+MLg/GQwte166JJtkkUR5eW7XRR6bn+digO08EGzfejc6H+22RU=,iv:0exZMG7Ms0qrctJn1coDPrOei92VGP+4vCtONW1EztU=,tag:Flm5sSMdsRpfNMWOH1YXmw==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
