secretData:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:ERrl1Oi4iJsu40/4F/jO+NFDR6Ad3p5GZwUGGSIGsOxtqxI=,iv:R4gHornCzXpwyznSI/znxow/8MYVf+SSnu3Fs++XbTM=,tag:Z+SxuQk3iL9xsgnes71x7w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:fuEG69X9N3CwbxciDVpz/V5FiF3oF9amYRc8O9dfXxkXt5L5W5uB0VHJTWWCVppKiOfQn9CTf6D7xitoBeHBPvSObgYfUw4N,iv:Ayu5sV7yfPEHjgX7GcrzXk19AT9vvRxxLy2w3GkUerQ=,tag:5BrZQ8cTOjC/mL/unGazFA==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:FlMSJhfLrIkQT0VjI6hTa0Y9ou0=,iv:HQlFLlzqh1j0deidGLh8Siuw9wCCjlK3/II7b7r7Ls0=,tag:nuUcCGJopp3OxHRLH84/Fw==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:JO8nKafp3jPFEASKDb7ws9KNU+/MIc+hXhL7eJqhM24pIQh3OapoxQ==,iv:JKQjYIPQ1v7PAs1vboQX6yilJ8lRt/2NQCHHTBe0ums=,tag:b+kEwf+0Din+LJdFv1Hafg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:zAOd,iv:Nc5YaQ4t9eQKoUp1B9gxAS3Ss2QQfyEXq0m1jHRBlf4=,tag:A9kudmriQKhHP7rgMGw7aA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:kq2zNpU1+183sH9W5mumaqmFGO4mLw1ms2yERpzANs/o4/IaSEt1zVDaecnsAg==,iv:j4+D14qlg+9qPx3z7+eLyItUJH/AtGMf80ycItT2wYk=,tag:lgkwSq+biXl/03cFaBdS+A==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:77CjnURnruw3Sss/sk10qY2QHqTuHZprSvx9srqMBNxOjr+m/wYGt6quTiHKjpYyKH7DiTBCTxPHaF5j17vkKUzx2yNLXOKTtBBADUyRMHs=,iv:tvHpUITRR04JZ+z7YerewbEj0rC4Pk4tyilQVfPxRCI=,tag:spoz3iSSBFZewdbiBWgjxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM08wMWY3ZEh3NWdlRFY1
            ZitBSERKUlljSUtkZHFETTJNeW1SUW5reWdVCkp4QjJEb1prT0xqeitVL2dWa0RR
            RzNoSy91VDFxWHg2UmdnMWY3YWpwVmcKLS0tIEhVZjR4WGEyRy91VDJhTVZ6aUhU
            RWxDN0JGdkRkdi94WUtENnBJUk81ZlUKS5sPK2Xa1vqUJjeHkACNdjRrgvhhd3Gu
            fWtnjeVKh4C8xjkctrkqrg354ABsSBWrxJraJVB3PEBqh3loH52lFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:53:03Z"
    mac: ENC[AES256_GCM,data:4rIQ2Sqh2sHGc0SXnzQ4g3wfbCuuiyuwDpY2Zd0O7fe0qvWb4CHHmrSK4He3ah1ivhH57ed1KQ+YnXf1qjkXV3j+/Knz9V8Kinae61LExYGWmTd/0b3dESnhwYBAe+Tx3ENR/mpH7tmVXMc9dVku/kp8672hnHdEBYljQ17up5Q=,iv:CZ51PdZuQYp5gT1OTE3Dl2r/yzHouCennn635oqoPkU=,tag:rOz0zZmDkDCtOGDgpP4AFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
