secretData:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:GnNb8iVSkm5jJM6c1tRqsrYXrmakSao59NKcSV0EmpodrsE=,iv:tCn8HMKQxCLpHsVYvLQknC8zGS7VXxUP8/HrXR5hZE8=,tag:fvT3EBDqmk4yJCzaUsUzuA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:7FX83ioRKzFXowjHjL+378MJSAvAK1M1PqTOgZyNbFtmW5agSpHMC4O/l8cj4EgiqRotHxz7Z8wlg+4mExklrhN/gQaWagzQ,iv:KqlIJOpSbTfUyhd0OQLdMsKKHZUE4weDOdQU7Fac/jE=,tag:2PuL9w3zMm5RiW7E7mE3IQ==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:UhM5Hv5npGY+cmKvX9lme4ew9i0=,iv:8Msg/2Hom95oqeDwPr5tpaqiyIQ7J+rWqqqavG1SY3w=,tag:bVfmtUAPzGD5q+lQ3xkRww==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:uV0wZVSRFERKWYkOWMhTSkFQ6na690oSP3i7Ej/1w8UPt0te+E+zbA==,iv:997o9qaHAf9IcaoOv9FHQvBbK89a9SuEYgR4f6IQ0JM=,tag:a26pVxEBJtQRQyH9pS4HgQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:NW1Q,iv:b+G+reGD6sQNHDhQRLWqncI+38MP2DvWYDIvAdEgMTc=,tag:OBrHufhw4C2Gt11IwJRUMg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:4XAtLTSIlwhPxu/nZ0WbeahsQKkauk+0eyzXr8ZXFJIUBA2Ao3fJ2wQr5DmqCA==,iv:+YylSrzQCF7vUPJHbXf9CnQCiLkOWv+Qd1D5K5fWV1Y=,tag:KPhSICgD6RYBVDgwoapB8g==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:YUkjH240eVyyTf13K5miYk2oQJ1Ddq0DRlyvJBSi2IYL9EV2vLAY6VGs1Wvhi6HAo1qKta726imwtn1u8YqYT/NBSRvVkTO8/kjlZnWlNk0=,iv:ojDSnRh5HW66SLZHABfo0dsKy8ZRGrDqIlInjV12kyM=,tag:kcc1wxIMNKQgCc+/V0CkvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ0pVWUF1Y0hUQWMzSkNt
            d0ZlN20rZTcxMUJHcWw4Q0FZWFJ1bHR5bFd3CkFOYkhzUmJnUnN2U1lLNGYyenZO
            Vllha25ndHQxUzVDTHVyajV1MFQvL28KLS0tIFVocjJzblplRlJQSXkvSVVYNU0v
            WXFsakY2d3FJVzFCcU9NaUdkVzI2T0UKiGvbEe5VMhNkYawKfjvmKdIA1CtLArZ5
            t9lH5lDiSpzWoseyIdRhfBjcX7jjExa+tcVujVR0jfBBmpcW/0WSzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T08:19:42Z"
    mac: ENC[AES256_GCM,data:y4a8r+PkWNRIBnpWn/pzwc5mhR1ni42dSIZ3ZRXEa61872UCmcuo7CouMsul1E/X5AQs52EKcIMd7UFm6v08T0daEb6k1gpbBQdLLEKMs/8ajy8x1FlGLDprIYXNKtXoGvdqgaL4XPq2AwkYtpeZXP01q+xNk/M6UE8pPYPvQak=,iv:sbdItcc0gMTAinI9oPNcx5GSwgCa7ZsxepFOkAbf7tk=,tag:p9aTD5t7VFtcmQBX7lBA2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
