secretData:
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:wpcCwIzRX0GUOs2ao6/YbaCx6fQq5il8y7xwDy3rf+/De1uvTfsplDscGEBsqMKQ,iv:PInAvihD7j7/d7X/90eq5QdA1TyakOniGOagI02HL0E=,tag:6cNF70/a5wTThZUL1x1Otw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:2xMr0QcG19jut0aYMJ4mK/EK6rricLdMkwiglu4YpFQO5aAXlWGqY3kJxXQZoBEyceHjFz6yJvELAPRqT+Oh3cuL6NJXgm/OJEznJfyDyUj3UubqBTTrnke6PvZDRNUr,iv:fkOiXZguw438ZQ34IsgBl4Z7DR6R6l5ZeaJcA1th8DU=,tag:xh469nqfL5yzbPcjIoudog==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:4z5WkjgFZ1JTLqoSCy4jpC8S+GXnsUKl8Dgs8A==,iv:cGlS1zdWyk3x+FvjfOTaYEGZ9D+rLkoYglDXFj0t4yo=,tag:99f1B4gLQDGauEXf9IOIqg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:IDMw6zRP1RNDQCzTZoVygPlazZlSoSXlQRu7XxkDn8PqNNBg5Zxv3khdcjjJ4mXGU4ElLVXYc8Y=,iv:2pohSoXpe7z/LNm73qus46jGkI8Oo9FzNdzZZ7XT3Vk=,tag:PxvFCgJBQty2jZBnF/VDog==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:RrVjBbuKqN8nrpK0APwFqw==,iv:4B/QoIVGTLcegJtBxedptNEq7UFR53wWM1QzHLIE4oQ=,tag:lLJwih9TMDUx0a2HVnm7mw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:4AzXye40isH19sXxPb/4JfjlFVEQPeTxKf7SRHg3a02Grkq3RAf8rd/55XIDJdL04+0m1+SKK9RGbmi21YLybw==,iv:SaA1yeDCnZRHAbHv3KlBUJqvY+CE0ME4dp6inZZESiw=,tag:E3MsfzKMSqHcuSzFa7oF9g==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:fYx8egrJxRcpZ2y35bL6+T/UcDl9K1W5siTnQEhIqzjBkhLGPPBEn7F305mJEueKpEb21dTGmH/g5yssoUHnADgXLJmhzvfePnUwniDHrnx1yDKvdHG0wDKXal/dgm0eEvJ++bXr+KLe5Ljt,iv:LAobntwUGl00YqZwJHSD6D+3a5OBlv50PAq936BczKo=,tag:YwL2fiH+hRkD6LEEyA3u1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT3lBRkIycm1mbXFVS1hq
            T3VPYUFVcXd1aituWE9QSHBXdmc5Rnp6UUhzCllTZ2FBakdCRmNrb3dTS1RxVlYw
            Rm82S2FxSHZoM0Jab3hFaGxQRlYyTmsKLS0tIENkQ2tVamJlYkFwanZSOEZvWUtI
            WWpIMEhpVHd1c0JFbFQ1d3p6WXFuWDAKVmkSmmh8GQSKMiWEboiOQFF8kEYmNs6W
            uaseWlMN3oswPXIyJG0aLbqjznR624YcIj69QlJIakHBTayuHExSPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T02:19:14Z"
    mac: ENC[AES256_GCM,data:GwCTDAoFqDDBZ+SKb4Qa/wI2p5O/kakFx3DL2uEFVVsbx8g/Ll4/x7CMnn64hrYae0BYitpeZbImdZnnS6yvWdhpDdHmm8zhzIAJpejRNsY8i3fs4G4T/Jo6ok9lIE3kAq/19iUeBtb5u5s9p2T/s1XMOAVNjqRq0PGuPkK0b8s=,iv:ecJyaJ75qMXS8KITM2zYKWfjAncybk53NohL/PzKfes=,tag:v3ZRJfi1+1PlVx3/QM778g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
