secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:MpkAJkuUAkr3Z7I8qUQvLOm8rPvgXpLXUePY9tFvadbNwg==,iv:q5eBrcJ0bTOETSgdOatBM3wXvX67BRsrAacA0CUF2ic=,tag:jdRKO8nK5mj3DLI0CPr/4w==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:qxqY9VT3,iv:FuAfBWmFZlPHm0Z8CEwuStiK9DIcjpUAefWNuZESH0o=,tag:wHEY8UI83oV/KK7VQgEAHw==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:QvXfYkMkyAgZ,iv:rW21WMWClGGfQLWGb3CZiF+xhWlWD0XJ5TvJsZOfaAw=,tag:mbJI9TILnONYylAM80MfUw==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:l0Rg/7SH/lxywgXo,iv:W9emQLXbkgbDizdLUIJMFW8IFZPhVde08I31p0GGFcU=,tag:xzp7fQjqoTm/A0O5S/bEvA==,type:str]
    DB_URL: ENC[AES256_GCM,data:1Z6QmCTdadS9e8QhSKkDXVpbIBSM8yrMWGm/yu+3GlOXTntCSm8HtsVQ9ujRjwlcMFL0+w==,iv:zl80iZa+YJw/BGiI2A3ziPZT7UKkgCcG7kR22jEgFSg=,tag:Vb31xKitmjrMNwcO8U3DRg==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:Gt0=,iv:t3qaPSZ2g8jEHHJS9IZWNaTwWCPFXc3y7nqcCNtOEJU=,tag:UydsJWq7g3krVEIKjbgx2Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:N4lLamsA6Q==,iv:XQrBuGxhkBAkqAc55QBIDsykf5zKIOLO1Zl7hnS6XIk=,tag:6+aahkynp4X10PpoZIy8HA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:DUgOgpPGRb2mmDd4CvzIYnY16j0i+0nqu/EaJc9J0tzD46Q1CNliswFZzxTo5TifZ5YboWoZKx72enUl7vr5k6oLHvm41tQWv5RSLpOAN4I=,iv:AWPRXEyJs4/Oawuu1qbThL9iUrXm9I29lTEihZhH/OM=,tag:FCKyNbs0b+bRZx6bSKmu6w==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:lKUAiVjNsTQcnY4ddfe4IKtvNVoNRHU5beU3sovbY+jvbc+DaHzBvOMLf/VVafuKPTkjKhj4YzFksMIq+8nJ3Ij+sE3vUj1VZlL+qn+lEXQ=,iv:NABBHfbsTddR2Xv2ypcUtVpuvFyJDB7Ms+fvAkuSUNU=,tag:pOO+QyR8hK3GUuNSSclT9Q==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:jgMIEvpv3yVhgyAIGCgyvRs=,iv:2dEF9YhATQs/KgOOF8V+BOkrlbNfLhBXVju89ie7Ykc=,tag:QG63l8VpaWXaTHtmYNu3ZQ==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:h/i1gU/WJXMS6AVHmyFtD6S6qlEADtvrolaA50KjYMc=,iv:vQ/WgZxZKGOa//0xbkR2/0DU1UwY+47CuevmMFnqHTs=,tag:92EOwJT60jNBj6nXXOIhXg==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:AvT6ZpMP6WPc0p8eCvRZD4y2D1j7+blYPIwRLSfqU7rWO6i5ZA==,iv:0EgFMpdLmClGvU4mrCHNZ59305QxMlL1TjLjx55JK8Q=,tag:HutdXTxKVwOindVsblXUqA==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:soHziiUttq7xQnm/oj5Sg1pp5HagtQGITs+FKH+2XDlhd4fguw==,iv:c7Mx0sMGhh5Mu1gAgRv0IXjXGcNmDW0z70B9y0S2T6w=,tag:/lpTTAVh5/1yyzDH/ITf+g==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:TziS2DqzZYfAnQX8NJzK,iv:YGURjDxY3wFNmmzCkVrF5POxJ+XLIz6PsMnMPW1iKtU=,tag:TYhhpt1sCaGulWBnY68H2Q==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:Byrs2IP8zk/6vJE=,iv:f2Cb145mmmyom3vPlr9jLcTHkWJoIw27V+EWARr7cnU=,tag:gdV7Gpg4N52UbhSVr0Mjkg==,type:str]
    password: ENC[AES256_GCM,data:ZPExANGmmUuU8y0=,iv:Yav5BUdPLNdhSSfU0Or5YLpKxRVFLDho68QYNQuGNp8=,tag:Lcux1vyqAmMdvvIhuDBrZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWVU3eXR4Ynl6MW43eFIy
            TXZHT1RNK1BZUHU2dEM2L3p0MHJhc2kzVkg4CmZUSXBQejNlTnlxUWVUblNBVDA4
            aWJ1Zy8wN2hLVHdlUUNVSklBaVM2dkUKLS0tIGZOdXFraXZqanlYV2tLRUtZc1BN
            dHk5SmNreTd5bVZTenBhY0lhMXhvTmcKDxYs/MriJdCCFiDSDwtgVHhZJ5l0Cf+c
            dTNMvNrEfCVYkNw8w9Pc1/5FLKu/TLUkOGtk5jnqDRyyfZ/84HgbaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:57:05Z"
    mac: ENC[AES256_GCM,data:dt3hgmSIJ+rozJX9IDM6DS1qOZ62XCk/fXSsIgtkXl/O4sVsbkmV3TVboT1Skl4nwNGEIgm9jt2UlsiRWvoyeydbaMgQvVIy604vtAtBrrN/yf4/90odK+Kvehlesk/rdPci1ZesTysSdVyJLvEq5f6tFkrefKeKLXn3/jO4sCg=,iv:9SulHICjKzWZuvUycEoldzXbGlTwukZgf8qYiDwfLjs=,tag:K7zZm2uT8gGUsyJs+f2feg==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
