secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:xeijl/35OBY68Qpnj2RYW/z3aFiEb2omrun2DH+ob6zLag==,iv:FSrddRGsK61CvWjN4KhlApT8qVMZj0VZy3E0bkcl8Fc=,tag:0ZBfsOI0qFEgnujq56Z3qg==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:v/hDJK3Y,iv:pX67orkaglzn9MoAeTWYwYiszoCAwa/3HKaDsq43Ucc=,tag:2eYX8cl3/G7A6S1K7uBFpQ==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:NFEQnongdHrt,iv:mq7m3TcaHZ2KCTAnF31U2cYjU+zzkRzry67s9rF+GLA=,tag:RL4sOCzvK9JisMyv5Brhtw==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:EWmRZPhS+eNCE73u,iv:Ke8svLMw/ymGX9TLVwpyFJPYgXABjrAylctgi3U1qc4=,tag:OojGjmFnCHU+SKDGc8CDtg==,type:str]
    DB_URL: ENC[AES256_GCM,data:DKZcuVT9fES/h9Y6FKkiNwWGManLsI3aFbWWniNPqEDVk5PKpBqb0zWDJxlnf+gv++AFVA==,iv:9BuybGrbLjRMm1PGJK5MlX7RTT5vqBzRRCBeCFiYxco=,tag:EIuyZxgfOs4i+7+rfevWcA==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:stY=,iv:ImMtjGadrQJ5TgOrsaAkaK6tqMoq3/cbvTEDFtpcyQE=,tag:0ovdOcV58iJ1PyhMg6/bxQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:G4hSZ3mRGA==,iv:xah3XE2ngwhnuTruvWdVeGqp8G4rnrad5kNN2AiQULY=,tag:QZylpUW+5Bd+Hbw1CzJh2A==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:ztOjMeGW4xylsof5b6ZchYR0mp6Beu2qeyorGQLV7w8W5C5mP0hguNoJ8+4v0q5vYC4aO1Rk4HBJN3UwB5k+M6VBM37rOOfq2qo83Flv/Lw=,iv:w5LzWNlIsF9Nh4gCNCX37DLSCwqjZdcDB8M5v5a7xh8=,tag:6WJ62t8eLzpgiqVL9DSnvw==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:0GOSI2Ji36S0yc8ZqMWRopv0o8zkUhqOh+88xXM/3u8VC0SY4NFUSZvYJWk5D0EUcLQ4za96hXbCRSuPiOn0pw8tjwm4isUeRrR6T+lgA3k=,iv:uTsZyCmMpPRCjgsJGv8LMrlCE7YGYECbfc/rdg5KVqY=,tag:nukajkEmpSnhTEIVTczqmQ==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:lqww7OfmctD2m1otTTsANK4=,iv:EpBU+nmmidP2JuQTlPWHcwNdZCsUblNrM+uQbD5MNjg=,tag:c26MrEuBbha1cnzNG/kabA==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:i/jTGITkcrGwK8Olcb0MsSZh2M/KwaJdVwihHu3zuEc=,iv:yYfNmm51EYNWuCXRk9huCio9hbHf+7xWFowZVRRWShY=,tag:B2Xh13REAMycMi5VppBTkg==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:o9mL/5qY2enS209lVs+l06ql9FIjDn8cll6NCHCEa8AEjHjXnQ==,iv:2WpNrf+jH1kIoec3obX+5ApV3Cj2l8wOtxbczY/QLlw=,tag:ZODGE3N+XwIrxHJDHSBZmg==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:5HwQgs4kJ4rLYg4YpLxxqEQ2Dlj0P1+gtxiU+F+FLwZoqMMu1A==,iv:HbOieJ0gPq3Kj+GvBMI5td+XvgrOM6G/ozi2/hZ4KkI=,tag:wC5AYGTY2K5fX0EHYi/QbA==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:aGn+xjEOEmLOy/kpN/ks,iv:n0UI+b/72kgeqfhDdqoSfl9vuGu3e6fHLwNS0IFUfxM=,tag:5rneGHzQMr3VMd07otr/BQ==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:XFtGCwjQHlwyg+w=,iv:ezGqoNsWVTs7wBXgnXtS/HR6m6DGJVHNjiKuFHyI1co=,tag:zxGir66eouqZ21SB6JV11w==,type:str]
    password: ENC[AES256_GCM,data:8e4iVXS5L5SQaiI=,iv:MMhPpMX5dhEb3o3+mWktqCOjpYLdKUubA45bp+3OJlw=,tag:4dOTX8zi8Y9XYkbfxyCQQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NExqMlhreUUvMkdBSmlQ
            ZUw2U243MllIYjA4MGkwRGxTc1FBcG1oSGpZCjFicXFmYUtHZ1RPWThxV2pZLzJq
            cGtCdzZoSmRKUXBOOWNpN0FNSnpVQkEKLS0tIElPRkcxeFI2VGE0MGRObUk2WXhF
            ODk5S1BjYllycjQ4TllNdUl5Mjg1SkUKxXqPqOVC4Km2Zb46bqwQ9Vb+pRj99u8z
            stgJlNa+av60aH6Gnt3O7Dfs/60NscD110slcBuYuCgnAixFYvJJhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:35:44Z"
    mac: ENC[AES256_GCM,data:jExSLm5Sby4U+3cKmMYKpsSG0eDBuFj8XR4eEbDv1JP0yTnRulvxeTvWk4/MpMPzO1GkjcND0VSNzgddU9AZ9FtfhQRznPml/uzk5B/wdZ7xEN4yieXh2KEjD+ER4tChVNb06D7btTxYu4hBUhgOn6s4kbAGnByFISmHiCsn3Cs=,iv:K7whTjML+kHwVsLaud0lLnxviNjUYCnwge87oexN2kM=,tag:PjlPANVk5UnrAGvTPhXP4w==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
