secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:RNF19TjdHru+slRg1ti2EP+9yWCm2hIVMLUvY/7R+YWNyw==,iv:3cO+nLyaAOcY9/MJOKQW5xqG/CI/ROAEl0k408LKTpc=,tag:/+i3cUL4GYbvhnLMmvZpaA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:WNNWXbSz,iv:pJ0r42vCT1+D38S3qpBSQMu4MSg+TPNlbPuOEGUeoLY=,tag:CkDLi1fJNpsnSkZN8LNqxQ==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:kWHlMqoDqaej,iv:UxR8mEDhL5NnqWNnMbG1jTjZLsTGqVPUMWM9fJNCu1A=,tag:hP23p5WcmeUjPPfXO4SSrw==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:o5XVF/C0MjMaOGBr,iv:G39BJD0UcUn5oCnkCP5yuk2K6gkidsO7VsggfRhYSMw=,tag:8AeRjEbgH2MVcCGwuAlidg==,type:str]
    DB_URL: ENC[AES256_GCM,data:fAWQK+9joT3WB6I2X0mjsqE5J6byYLttrjAmInrefexQCbc2pNA3lXc7MYp4b7061HA8bQ==,iv:Mq8R9doDwLuz9ud4y2hZdf9cysWZVMuItOhEMBgLUNA=,tag:vJxntqYiEkTP8vmkz3bCKw==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:6SQ=,iv:pjDrgH4G1OPofuaiZIO3OxyVVuTQfXwt2utPpYXYOAI=,tag:KsAlQuupipmN2cHFyLUZog==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:HvkJOFFG6w==,iv:7ko6uInPpTDKNudV3JdvS+IxVREmBCRo9r63Ci3TqaY=,tag:uFBQa2W1e8yfYzABv9k7Zg==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:ydTyc1Iox8GtuEUsU3e6kTRrth0Sp0imPle138JhS9bwms9ih8VPiGp4mV4HYPyTzpr2zcY8D2vWKs4pV4/sx6lJqrbFjQ5yK9e1Loa8uEw=,iv:/F4SN08WU8AGkQavdEn4nHEq9CjzWM0ALiSz6pYQ6zc=,tag:lp1R0tJ2QdxTFbImtItY+g==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:18mjb5xjbz0dfOzhvOO1ait+P88+j0ddsSBFBSyGgPullDeF064VO4nm8x+iXBNoCAydqDTer5w4lAc+QRY0a2VpQTCgL5NXnslOjTF+Blc=,iv:C3uBMq3QI56RshwMrl0iMEbs2qnyyKHBE9yGcsVZOFQ=,tag:tXAQKRYxfdAqVlbaiHP6zQ==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:vsS74H4NOxJYhM8fvyp6sZk=,iv:5zO7hys1TImFLtZiIPJyggG4wMoyz0UuEfQdNUxLNtE=,tag:8b1nJWxM/OMXs4T3SIJQeQ==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:sDtaSKi09lrHCbIxaK9OP2B9fZOEibKID6M0gxED414=,iv:tW6/CNQTZl+QpPcoA+RtHOWJxatC4zYsBF1240LDv9A=,tag:MQjZduKcfsOdVvJUf89w1g==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:ODh4dZsWb1BR7LjjIFZBUmkTqRyHKqq/PxiPDtrsrQOxKQfqzw==,iv:XHEd54koyjTDHW5vpNHo7EtviYESCqu31xSiY925XOQ=,tag:sZ/vLUzmoHCpAgCOAwgfdQ==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:qRClH4BGtcrQh/leGRBT15wZ0GuLLlOgmOitSeBO0OSeOlwd2g==,iv:Zt1YByi5WTZC05y9c3HhQMWoyEgtKMfSu6l2b9CEHvw=,tag:D8XbffCDLQabLjUqqL/hbg==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:Lq9JRQGMfsJGtghNTO8w,iv:bszTcjQjlO0SDCRJfTQAa1JZ5c5Mc4lzpLFi5xtQKG0=,tag:QrJK5DWF6/HwGU+LITil9g==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:aEySO4cwH6wfPCQ=,iv:GqY+AyYfufmpXBoyZEiVy6it57iIUKLvropRCSaIspQ=,tag:xVhTYnCoJK7qiNI5GzfrVQ==,type:str]
    password: ENC[AES256_GCM,data:sEkOxSHvbxfp4gg=,iv:gMw/u0nGqPK1WR1pqSrkchHZUZB+8SG9hxJdg0ta9QY=,tag:+divxlmYfbORAQNFT2XW3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUENsVUhPc05Rb0k4L0hr
            b1R5QnI3U0FHSHB3ZlBIdGRNUnhlL3I3SXhvCnN4ZURaNkswczNSOEFNME9EVXlt
            dVFqWVd6SFRQWUZRVk9tUCtrZUp6K28KLS0tIHRxa09UWTdwc2cxRTQ5NWI4UFlm
            RVQ5Z2p3ckFnb0lWbEo4YWppWWpUMGcKVa4gB+y5inCZMP1tbOAL+UDBxCDjvgnu
            tpr8UhqYAO4Ula4ffm6s+DUmH/D7p0X8OZ3+S5v1CQ9NR6AkU+aHLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:47:04Z"
    mac: ENC[AES256_GCM,data:65PxtewCJQmdyFP/rNfTQ7xSU7n/k9cFxONEOxbO8EpfQyc9IHVPeYbfHCDBYqkep0fFVpCgg/0TUk4VXtsde7G2X0NOSuTIRG08ZgdCPstZZ+5QHkzZKI2Botqse+7/2euk4y78ZI78ajzgTCKEAUEvzeUpDH7rthA76PO+12U=,iv:vAD8dFUKHNvFcqEA1Nmati0br5X53GTCO+TWYYGQjFE=,tag:DB+aQ/reR2Yhp0jlDODiIg==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
