secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:601A3hyaEClH7v4B9VR5RJOeHSqHKgh9GE8kQYMKgwz0zQ==,iv:+lZQhE22jmVHU1XNeQu+1U18QgDUmjwPHqqhlWvAkXk=,tag:WYyhnilA17U2/3OR1QJ9Ag==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:87aTYvuT,iv:TeqDlriE3j745LHlwoFeHcjsgH5rKLc5O/z7+B/FJWo=,tag:RxusC/YGkWeWNy2hN0D0UQ==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:37CWjsh55FXM,iv:5hnmHVvHtdPHgpQS9K6r2C+KhvcV1ey5cJgu3GLjDJ0=,tag:+uMmjXN6y9+vxsJhDQI09A==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:NXRy/RpRNKfTHoCA,iv:Nh/lqNSJPX/d7zTGg3ns0l3RF6+CVCAF8OA/bqSeX7o=,tag:F5E6S5UBeNWnqqbTKwgO9A==,type:str]
    DB_URL: ENC[AES256_GCM,data:+29WNQTw9kgcKOYFtVpXsPd9qndxIg0X29lcRlrE5AuFonIGORbZ6l9OQRAlKzug1OArbg==,iv:Yw4XqnK8GskErQXwO6j9P5VOP1rCxBHJkQrJrZfoBZM=,tag:KMMUX5YEozvtwPzpIU2mxg==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:GH4=,iv:z2c6+sKjhjQBEhAWrVtX9re4tz5iAcOOODdxExHvk50=,tag:NevmxBOXd2m3muRFO7vkJQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:JF+/BlwpbQ==,iv:Cnd/Y3nTXA+8gfb2tattbOzMX+qES9dGCkLKhuObgwQ=,tag:tmIlYcR5ajctFnhDKHnXaA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:ycQmPQxpjQaqw0LiiZtkX7xnemdP5AZROI6TRVIdQhBnxtqfJ7i9oNu5RC89uSFhUFB+5GD+6tBsr10zjGPirDzudFFVxrbXa11Cm8dtUAM=,iv:Wpm6nI/op8JHRnNuXwLkDVGfLRza4VfL1b14j5yHnQk=,tag:SfrNrvzFPcsGHNQV79YyKA==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:G7Ou5nmtaTOTDk35+4P+yyAw6dRzMiaqbp0l6b7+Hh0Gg02UC4vCj8Jy2ydChKoFUhkygMUZ7caqU6YgFBJ7lCMAYE8v9gw/dKk5N3v6Rnw=,iv:wc3iAARVc6HCK1LworN9aoz11wpfWr9+SVcBobNliBE=,tag:MqQGmIwGMillbYwqZgC8lw==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:V6IF80qRd5Qc1T/sVyw3w1I=,iv:/oZF5/aiL28yAn56DxaODUPwkpx+SNGApVWtyWNokB4=,tag:VoybO4lggoPy+csF3m2qyw==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:sMg+ujci9NI05zB1WocSSpGkgdU5/quGPKRNB0XID6I=,iv:pDgy+qd1nPsHT2fFhkNPsjlTBurhWn+5Dv9PhORLOAI=,tag:LQML+1xinjTCq081omc8uQ==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:wOmZPvPQEX0J9WfHqX7pS21JX2+k6J0Ois2UXGBdf6Hj64vJLA==,iv:OVsGVUZkOTl9FFTdRif++k50EOtMr8u79ioUE77jvrc=,tag:FJ8VbbV/B3rXRhFOonQf8g==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:9s2Pmv1S/jQhoVwSM1sgIQVOsyTEnsTtMPyZa7p0xGiUgZ65fw==,iv:R03reawm3oTUXFmj1TmCSvhG/YWliQ8XgNJPLk8ZIpc=,tag:iFOi1+S08kWV8tqdQJgnwg==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:I96kSf/kTJW40ONGgBP2,iv:ShCDGRukLAk8pMrRVGBhcJ0JczxLEMfrbqzYmOC6Di8=,tag:JYa8WiK+YiM7DnLMnye/8Q==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:UG2uoRdfBFiqGng=,iv:4X0+lFlS6twLQtpq68zENPC4/nZqXJmHci0lMwaoN80=,tag:NEj4HYxcIVqWK1MAyG89Cg==,type:str]
    password: ENC[AES256_GCM,data:XLyjWjw//OOK00k=,iv:gTUDmO9s2zVLTy8VYd4AImsJEMqIb35pf9OvF8b7QJg=,tag:Jt/f2ZL3GCOPQIlS3E/3rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMSszbjYyZXo4Zmt5cS9T
            WlluUHFOV21Fd2pFUkJqaFI3WEVtMloxc1hJCjhsN2RqdVBMQnVmSEpOcWg5RE12
            WmZmMWhPd2ZwR1VlYllqMUFFWkduRzQKLS0tIFA4Y1BrdU1tSUNlU29WOGxTSzNn
            d3lweTRkNzVFWTd1TzU1YndCMDdXMjAKjaZ/P9QsOT1WdNXdoTZ+bqYK3wRQpTaW
            JwPxzi38YedAX0rVUpSh6tKRfcu0np22hA3JJ5Nq5P4oih/SsQX0wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:53:06Z"
    mac: ENC[AES256_GCM,data:3B3mALBBwfNcPdAVcstDNELrbm8QsuBEPg6IJHlwamBt0VR7dNJefEKDHuvN7SPujAS7m1Dc7b2fJ+Pl7f+u8LsyA0JAz0ipDiklH/77erU3mB5vVtR2bPegGQwlfeg/dTZT1aYmo0lmqRnH8kw4OEQvxjSfqpVCIQuKoBNWgzk=,iv:LpmNZxI0l1EUdm/U3pcF7Nb6vXmQ8vjCwDh8TulplVk=,tag:5XhDszSVXmfSIPeGiRB4HA==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
