secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:y9p1tK22dlh+IPLjmtN4PDYhQMBdxuSkSCuAR8TDdZtZgg==,iv:kNaVFHjmCadrNYwEfU8OHHH5I6uverCuHuL73lumT8E=,tag:azumK63MzGCLzwK+HwrUMg==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:jMg4AB6P,iv:Yxnhi+QTppGO8aN7q8IMpqBkzNdgziHCyCqKogccEFA=,tag:8nj9SNbTuDZbWiDX5Fa2Yg==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:+eKsMfB+iZFq,iv:SHoDoWgTIz+xeFb5/68cYN8K6ZjyjmKhijzfLpJluV8=,tag:TIRpqNOKsTrlS7xyzHd0FQ==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:rAILmD9pJH8dNc4M,iv:RaqwBkUi72uYith1gfbf9+ZjldhwFomPKrfaKaoyZQY=,tag:JRvmqYa1zuOAFdrQwV81zA==,type:str]
    DB_URL: ENC[AES256_GCM,data:XyTgSYzef3Pvetn1FqPseHgv+INc5V1xHuHaipKGyLRPGZlTc8hAZ6pskFWc5ngqDMM1dg==,iv:r8zhCE8GRdSZHcHJCobGKCMZjeXSQc/lnjoDYnGG6gc=,tag:X70r4bZIzUG0X8rjdh9FDg==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:m9s=,iv:/CtKXFz2F/JeTQQ6ewzXWZLFCI+rELdSNL4g27isr6U=,tag:KeYvwGgcLZvHwStCYEZ+LQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:5zq9qDnbxg==,iv:nyOK6fV4kQ5MLhSv0FPQ6J65vwGNKwEFwoPhjV5ZeJE=,tag:BGCPqw2qOeDM+fy5rNBtEQ==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:JL/Zl0WYdq2QjdnXv6fCmqLSQcf+XlNokatwjr/IGLI+Fid9p88rCYS6Bj5SByxYKqSy6NP/Vu9KTtMYm5aPXmFU+M08uhdsLmmXsEpGNzk=,iv:+4yu6j288LZHuD1jIsM7K4Wftr8+1peybEn0x0enCPM=,tag:89tLMr4XcTzV3xWYynCL+g==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:spFkvJMrH4/b0M7KI+XMie62BpwYZ7Vsg8w7oBV5Q2wq/wtxkrtPoLz5ZHZn+FRqk03ukunLOAqiESUned9vDIiMFI33aIOW4T4+qiKoftI=,iv:CJO8Yhw+ZNu/vNVNNzb2llyjCwqrNWZCCNlKi4geFls=,tag:pV1yyrAYXCRvcSReleurdw==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:84L2a6YMKyKNE5M+AWnMZ7s=,iv:I8hPZSizq/8Qbn9G3Wq/cQx2S789aazR73rNFdAJd6w=,tag:G0jgxbDQgT+HaiaAw4zH0g==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:/o6pO7bt0sebnZkFFSjvYPFe7w2iYGtWABLkdi1J3U4=,iv:y+01DzphNSI5Js0EQhmw2OZvfEGpo8x1Xo8bghjhaXY=,tag:vUD0DBBKpiUVmTT4qOBdZg==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:QniMx2vgUtRUVCoZp+X+BHmJjbGdxHLCw5H73mKntKMHuS2BYg==,iv:ROEytrjVQuG89qHZWts8/bcrFcJXGPRoMOAOWthpCnQ=,tag:MtXlLUQgygGHSeQKgjDBsQ==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:mKoz3IMC6gwAncpKxBkUG91bByDvKS1+sv1+U5P4qLt1mpwnGg==,iv:DiavF84LwO+aTgOhPoFBsOkjg3LxeU4V9Lk+UgGnYXI=,tag:ZgDnfhChR5QbghfvQOqz9g==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:3AIUryTzcBZd1aTvHxNg,iv:iYuD1Vl3pZSqpJ7adGSMdWDfFpGcC1ix1tuzkoeFkcA=,tag:RpE7x/xmPWYOrBGplZF/JQ==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:SodenYhq/FOZxeg=,iv:ftxwXMQudyK1ukJAo8/0wvw1UtEaxEYriaCM3ZQou/4=,tag:YENYDU4a1CsUpRENfsVYDg==,type:str]
    password: ENC[AES256_GCM,data:2R+ve7eg8O/vAe0=,iv:trmNFTka68J8p5db7au+qiSJY+A2v41szuR7m3gaDgc=,tag:EBe1DWCS2/WaPK52exai1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3amptTGVjV1ZLVStFemNS
            Qkc1Qk9Rc0JlT1NKNW1BWi9YNGNQTndCakIwCnN2dUl5Vlp6T0lsTVZteDJSSzNn
            elZBTkxjeVZxQ1BCQ0p1T1FHTDB6eFkKLS0tIGQ1RDVTQ0tKcnBpMTYwZjVwazBQ
            VTVpdzYxK3VZNFExaVFTWkdRc2VHdTAKQj4C1idjmFWquFuVJkBzGYNk+rGinZjo
            dPxQXi0Wx4YMawRFhl7LVayLvqMc+Y2jgo4H398CuH7fMiRrcC3JNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:55:04Z"
    mac: ENC[AES256_GCM,data:XzM95SRXovkqUMIPr5hySz21miioYtEU9DwMMoUPYNqxxG/bJhnadnNdZGnBDPFzwPhxNwghDD78hgLu4Kcf4kT9PNAHfgYbeFEvrpFp5UgFqDpQJ1WyNBaY36YrMjdePbGPa0xBEcEutwrqDWLKvN2IRuustENL/EkeONlJACA=,iv:v2z+JDZxkuEVF5OR/bSJ8I3PG/BlTHlPP9C+8atWSrk=,tag:gSdy+WeGKsWO73sTkG7j9w==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
