secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:9vTcsX59Wm/SIPGf83Y1giIoJmZl6l4sqRSkur1gMhH78Q==,iv:IaB2+ZhJEb3O7JhjXcVvPLDgCjESnFCGJv50ZbEgHuA=,tag:XHPTkd+9Upe8sN4z/5Y5cg==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:41RJBNFw,iv:OJyMlieIYY/aIOm59DybnL08C2egVMMOGdvJ1zj0mOg=,tag:mhkuS4Cz8fyEvrw6eGyHOg==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:HrfrcYGpOYkt,iv:v64ott9SNSZV+Bm/NunaEczDAIjTtx+zPPZnhOUS108=,tag:qGt5jL4XNzuogg5rJBTRTA==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:o966uu4db8US8Str,iv:VSJwfJ6I4ygIWiTWrzfKbdq6uhecdVy8TzHtZJ1sR4E=,tag:wN0L+fQW5UmBzMUG+NIcMQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:NyM6ibUlyIkj2caapGthM2LYjgGkkenQbztMScwpMOolufaDRFM5AKuFh9Q/GEzcSzF1UA==,iv:+N9zqNVnqdtaKH7ZAnFd53tXMCQmxgyAGqA56v09V3M=,tag:tpBQOxUYzhx7Z0dAwTyz9Q==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:Ru0=,iv:WumOZDbsxPASQ3USTXOZDO+JwIjuAbdQ/5ffNVpfexs=,tag:ZwZFtWE/yUQCp3CTwJRX+Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:h722Q1S6vg==,iv:SvOIhwCajpkTfmqDMuavu5BBivqEvVFdAyBcYbJoNu0=,tag:S6eYYhj4yw6W0P9czqdi4A==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:eDIxtwUmieedHxmW2tMVv+3aofJLF6UwmSIvy+oVUt+F2f5rH7ygrVuMEnAIWC4hVffU1O7nl6SFyMW6xcTTDRj7/kDuKWQVYHbrBO+wTZw=,iv:eP+lw9kqi4+SqQndpJC8oGoFeAbE30lEpdfWRY7U/2U=,tag:qWVsGTT0YtJg+X5tNzFflA==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:jJbfA0FbZEsXZSDqAGtgkbGCH9rauG1/vwiLirH6zhO6OxL3RMiHzBsM23EdWaAWaABNUdoLkZuEiheVAdgLgHVFOgu2L4SehwNcHOUCDQw=,iv:NQmH6UsgPtJk4QdKUCfW2YLZ55oddMaTRyB6Wp99PPU=,tag:vozNqobNpDRmzI6o7XvW7Q==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:Q+Elfp2DLgnqoSad1HcqAHY=,iv:XJHJfobBQAGzrz0KosgIeMXuZGAFDmRQsClFImfwNY0=,tag:dRN3Ec9UDf4GuZORJUuX5w==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:7HJkaM9G7hjds708x4qmzCQLKAKUQ6djF00VZkTtf9Q=,iv:/5J95pnVQbokoMOGxcawfbeAmgjn/J9uNjwPuJqxvcw=,tag:2t3TU0XX09zXiZTSXBAtfQ==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:BxVQJTGuWzSqS2zkuj1HSc/vAEmEoM7YBgXUpJgSstpoL29vtw==,iv:u2M8p9iZ3czwODYXIR31YsOl5YNW+CwPZNyT6DxaoTE=,tag:54h+N/hS/dItwY1NHMcf9g==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:IAgCt4wglXFJGC3BdsMjUpgUdMDyo4e22XL4Cuz7CKOP+qovBQ==,iv:Hg05arHDM9yS39rWYK8acvqK8iElIrRDTF4pi1q2wxw=,tag:Q3tGELIJw0gZR5hou5TQLw==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:EpECFzI1hm7VjZmq8RPf,iv:UAQnbWUFUooKIO28a7LPFPlAddrYJq1CZz5HCDUMzTk=,tag:o8Gi7D9BrT4AA0tIYtffPQ==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:+5Gl+dDP+vIxxJM=,iv:WbtFbshAHhFXAy3A6sR/MnZ7hORxXWoH+iC9QvFXTA8=,tag:dBFGRHZ1aCl1smIpjf8ctQ==,type:str]
    password: ENC[AES256_GCM,data:k9CMX8PHRDSPJQg=,iv:DBMkt5LHHhX2Kqoeb01lkC5q+v1HU2TLtr3kzU/8VVw=,tag:FgrB5aC2sF9GosqPl0ZEew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNVZtcHRSK3E3Yk85Y2Jo
            aGl6UkgwdmIvR1V4L3h0Y2JRd29xRmRVN2dnCnNvQWdlR2puZGtTOGp2R08zUmdW
            RVdFZW5ab0F3d3JxaXdnNmxudEpZUmMKLS0tIEdaU1ZCQlgzUXpQdXFRQmF3ZUhE
            a2tMNnNFeklPdFNveWVpaDh5Y1FMdEUKaEwv/hl0IedPvst2cWl7GIMhk4YqNYAY
            v0mpWnFlyR6VT2lrC0+JIsKzXJLlLfuzqgpyHKRmt5gxmQrBm5JN6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:05:10Z"
    mac: ENC[AES256_GCM,data:xT+rkWgLIbT0i9I7MueZCWxjDJ7KqwLIghoxS+PFnYch8tIFAYezRi9DQ5q40EL4Qck5XR/Lech9Jt5ngc5zoHdMRE9N7yvbE74zcq72qZwwEfLq6XQQgoGzgPoS7fT8vtDo1w7VU7ZBk7siWdxKcsDvWC+QZkvLAZRPGpZ54e0=,iv:B1t7zn5XQEVW3JtKm3wO/EmrzrrxeZv2q+hEkmOnR1M=,tag:l7NBiQcSorlKaP6W2lN/+A==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
