secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JLpgr4ljdnBL8z85HUkKzNUmOikopD/26u+7KDMqt2tB2Q==,iv:2nzm57BI9pJivXHju7wADiYkm5c538Sza1DHA0TDmdA=,tag:wjd9h0Q6O1sgwMfgKSwfYA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:O6Hbaz02,iv:+gWXafKs+ZiJcBS5azKnWZZsqXps2H2OV+O5HctcpZ8=,tag:9lplA/qBorIoeVaN4rOaSw==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:frbWO/1ESCJs,iv:/pOOeR0Q9sUEYRoaJiZ3xxzYb1AopZpUTk4cLyrvTEw=,tag:GfwvzFlYrimGK0yx+ncXkQ==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:jXQaqz53jRdyU0MR,iv:qdrMm0fgeU04D1MELCCsILPXnwCZ4Ca83g73k3qIf+s=,tag:HX8LWVxZo4GThmFcPImcSA==,type:str]
    DB_URL: ENC[AES256_GCM,data:lidBra7l98qVshijAwI2mNuygqPafWBqLxw40xfl0kM4tmRSsU/OgW3w1lDuNkDrRgKjbA==,iv:OLk86DylQ0R+KaztkwEHrq7oOMKeAz2FdlnxCE55C8Y=,tag:/87bsm+aVG0qubjGsy9uiA==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:T50=,iv:zGHgopSm2/g04rMz8BgLRDIdqitv6n265QtYXQQszgk=,tag:zcUhCJqTkJD46Erlqgv7AQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3sHcI/hTvQ==,iv:RToCm7CRU1NfzdTUBRoi4EsQaQstsWpVrWH9LqnUl8A=,tag:2kdAzbpUxCJhVNEjVqTqFA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:/1Lw6AQDPLOA74l+nCO4Qp2dDAgE1bIkurf67gr6DOFcVgLgUWOQPLVh21xI/RMbzWHIHdWb292DOT5PY/M6fSbEVBzYTzMr/UwyYezFyyg=,iv:xs86ouEC/dNdXXA3PiUC9FIAVG2A62xtxwtui7s69pw=,tag:8PH4yqIsFNNHxaL5YAS82A==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:dAwZuFYQdxb0CTIhitm2EVWYxC7XVtFIvyFRA6aI/e49R7q9JYOnyP+jlwhwSOYykwcMrmVnrnZoBsWzc1uNJPgI6h+O5QtezILMslxV2gI=,iv:1alePR6HzlabXlO+TI/Gdl62/g2ed4A/wHb65u3SfNI=,tag:PZ+Sl+UB7hOnIhVb9HL4iA==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:4jLSwS5lzdkadc5MwB1sGac=,iv:5eoI4Yw1zBVybCTe5XY/eP6vzlHYgPHxUYGakK7uySo=,tag:kaxR/Doxivi00V97rQCrjQ==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:Y1z35/qhJKYv/LT9ScEkAcCCctKMgriEcDqTbia/1BM=,iv:q5r+7ih3YSB5bp0ZSAEZbdfEnPAlaN5LxO7W45LXcj0=,tag:9ZgPd+p+7Us7KchzGLlIOg==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:UdsUec83a+iU9y+2s3jPT2NEEy+Rpt5sHCgIhlPXkiyRGbOAtg==,iv:nWCGDPpS2kBMSxo9+Iz8FED/ArcGwt52bEhiQi2BNY0=,tag:wC6dTEu/fDeZY/6SNDIfdg==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:cBERDBun91biX9dkmEIEbiuIZR9uQif/ZtVTDZaqI/qOuNVPGA==,iv:ViCytnSmrQd9U71+gGgwN672MNUqHTeWxnkmM189Lag=,tag:6nULCa8LTmuHnUusbL4yqw==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:1ClcvCxYjAX/nNhGfuAQ,iv:IOBcmjLZepqUXbFERDCPb1QwECXeQG/NZ6YsseJpLqM=,tag:c4twsid3vgH4pGy+QweFYg==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:IQwPgRLZ+3W8PAQ=,iv:Ag6dj7Ex+Ksf5egYmEQZOja+DAcwBTHlYonFmGedoXE=,tag:Iquor8c2nYRL1J9/HKq+hQ==,type:str]
    password: ENC[AES256_GCM,data:2CxV3ERDRM137Dg=,iv:BayFq+f8474gUDHi9VdX52JIQMjqJGboRj4sVo9shN0=,tag:M+s/vNKcBIsWwurcLkf34Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcEYyRlNFcTcwZHIwdDhG
            Ry9hemlQUGZvd0c4b0VUdnQxd0dONWV5Ukh3CkRKczlkVXRDNkp5V0ZoZnVpVDRa
            S3k5VDZSNXoyMzVRbnlENThPVGJiWnMKLS0tIEhkMTc4ZUlyZGZCNk1EY0dGcjFM
            UWN4NDZIc2R6Sk5xT2FwWHZnTmVlVkEKAcnEXk98wA0HlJzePs8YK9xHHNShIFak
            U6NqrOWzb1x1fp/1Gn+VaBL2HSXKQI8+EiDwi5SabcqGepOU94PMog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:09:05Z"
    mac: ENC[AES256_GCM,data:qnyc3GnZYHFeWSw+uPFh2fEZDNx6eyo/YmE7wqZ+msOnT4gx0odnFo7OJLM+IZVvxxHaC7UjlZSVdrtxi1RDTZo2atYPoPGQEpM9UXVlc62Rh1SaSN+R7xb3NhHRiokSzHYZsJuelROtPaXtpw3Pg8CEffihLTu5fnTJUq3ieIE=,iv:4eH2aAgbFIOkUl9cEJdg9oY+q8sQ6VhdbB0gf4ERY48=,tag:mO5ocLIppNB4e9OUC/TAPA==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
