secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:5p0wIGfXAmhg0NjyofyvLHB6J7rS1XnuE+03ggGzxnHHBQ==,iv:Kq024wkFCT+dXFto3Yq0tY/sQMbyL+CqJAKKkCB4sWY=,tag:RUx7rWbghisFCIafIwTWmA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:Vzj7PfS2,iv:Fgvfiric1f5fA+zCWze+FWqkitc+XC2Kg6WlitE8TTA=,tag:h5ZyuBaOb9aEtifrbjUZEQ==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:QvkkaFqQVzKx,iv:Qb+HcKpKNyfDPBpzZbgauTqgOXZ3udRgNcNNNdEGckM=,tag:cn04GF9hM4tFdCdagcKu5Q==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:M6BLcvsbst5uh5dQ,iv:keK760OXPcZ1ZtEPEkhpU8fvtZ2qiRtLzGb60+EOmYs=,tag:vYn4lmV/HTRv7PXyPjqynQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:Oq9r53YFxYIQg5IT312NPGiJ7KTyc5Ol1r/7dSJEd0ObSRjpL4qxbgFJLPlZHufzcdEX6g==,iv:gqAXE0FhwiOhZIM6YLON1QUvubgQUjUnuHY8ITY9phs=,tag:g6+dtHfG3pe194aw0YIokw==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:m/E=,iv:RGcgUjw2XciOAh6OoJd1LZM9JPJ9xn5i1eVs8XC2cvA=,tag:rKlu5wLEoCqsQzFpUxBwmg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:JrF/3eoxFg==,iv:qUkUkn7EIvrpZcUYCItUqWfN76ZLwxTauFxRTwXASzs=,tag:cVs6oVb+vj+cJmUShL6dEQ==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:yeydFvaJGyH3m/97mDezxPZi1Pnla3can3UEcCVMi88xUcxZIPjSoTmIddPsg9h60NUjCINZrUf/eR0ziEjqAJXYcKEnZwMp8p5s9hdn3FA=,iv:9zWYEQZjEZ4GfpgNMLHhbsT/MEJyBl9QfIhNYezDbGw=,tag:ulbvWMTL3K++x0SLl/gTAg==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:LWws3V1QGiASjWhvZo2g1tNrlDUYD3616lbNIAziSegiacPepbK/M1iYix1BCb5NzAbA51+/1PCD9Gm3TySx3DAicOgwvpki24AAj3NoUkg=,iv:rmPjpiLYA0hs4LOyACJjqtyd6a2cCITik8U6lh8ULCs=,tag:egxp8cVeAM1MeLVdFcuX+A==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:5Oo/vDb9T/0xbofhdwkJm+g=,iv:GxyrhjDtWYLYEhY0o8Wi5VcHFSx+sKR1T6uPiC2aKVA=,tag:Z49dU1VBMJH4ngLVkUVoKw==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:HKL/T6+O4k5Btj5nm8gddPY8mjocf5pJhF9uCPTw7Io=,iv:BsNXdj0a2yhaJk9/rSey8F7OStEVxrMBxsXrUBi2XYg=,tag:S+gEpyVOhSY4aE3N0tBQ7g==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:ewgzrUW9NCtR+GKkArhnNmGxTngvR2rBdZ++gFHx0PIo+n7uOA==,iv:sWIi1f4BzkqQcaJJK2QCbFRL4cNmudwdvs8l0UnPehk=,tag:sGa7zEoRFV36n5ys/C1RMg==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:HMzXOt6x6OfvkltR6fnbI91R9nw51C/C9VUG7zS88m77s4IM4Q==,iv:okQKSoo2SXjGuyBDkcqARcJSKeHURyMGsqcdaDyKVY4=,tag:m4H9trPpCO1byn17xnFNcg==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:Uw4FhtIrtIbYWiuxC6+f,iv:vSYj3KX8mNGm4IJ6taDGzkHwsMoBaIm+jnuilTw3qJ8=,tag:C4GNcJtS+45MG2d8x3/k+A==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:wJV4layeec/TrHI=,iv:nk4XBngbdkMQkyb6GqnEO8k//GeZOP9Nno39u3X2r1M=,tag:eJ13LbJUVr2azJ/XJ54GHQ==,type:str]
    password: ENC[AES256_GCM,data:3Yl7rZlAxdomZdI=,iv:CWeJHU//GapUD8IfYkW7d5gh6+jJj7l2G///PNzc3H4=,tag:GOlRT51XVt+7cbbyJIpeoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZVFQM0cxb0h4Y0NGZlh3
            RGw5VTIyaWREMHRJSEkySW9QTFdKLytGTVhzCmtXMjNiZzAxY0grMVJIQW5RNm5J
            OTZEUjF6MThtZDI5L0swSEprRVRoL28KLS0tIGppL0Y5N2RDaU1PbVJEVkl6T1oz
            NmpVM0lBbGFaNU5NNDlsOUhCR1ZKK00K+zlCSRIozWeup/Lym7StMAu2D5LW6CsX
            Cv8DOlXhfCpC2PezXa1DvqFbPmhkcDD1qyO0zT39nyb1Rnu3A3xCbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:07:06Z"
    mac: ENC[AES256_GCM,data:bB8Gd6kJKkU41tz+F2PNKZfnPWwlOZjmUW48ognv2oqvSL4lsnKW9CwEzQYBUjBZEFFLfhbKv8wAs005URFfCaFy1iFYFCcyuRD+J4Zt1PdacS+XAKiBZE1onGBki/R70Eoui7n9LLMTQ6+gHu+77m+9IlYbrYbt1AVH2iZZSTU=,iv:XjAZ3w1z5BwaMJWxDY7MFVCnPTzHdsQm0q0mc3ukK08=,tag:idXnDFmCOX7CpoLWSc1Ucg==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
