secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JAJb9033NYwio7/ZqlALmLu4X+vF6gkUN1S6v3T3JRlyww==,iv:GK0CbaE/p0OFsBQSkA1NWOXHW/7gwQ0JZMMLgSS8C6o=,tag:+JzGdqjr88fXqwJF7beHcw==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:XVzjvaoI,iv:LG/g4JVgA/6ZaHj0C7qZw9xCt89ldqZgK8fl/rBVncM=,tag:xPIQttOAJQ5A1f6LXl5hfw==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:FQMG+58UnE9A,iv:jjPys/Xuzs4jD+qHaYgu4COVye1ewqAyNfFmVEBEtoI=,tag:zGztEVDkjheu2O0Pa/fdMg==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:8CCKYnZO+yAYyc4D,iv:SWPykQVyFID9u6E/rSt3EcduDX1d2stsMdBhx30Zaak=,tag:lM3d5OCUrzp8i1pf6UOy7A==,type:str]
    DB_URL: ENC[AES256_GCM,data:m/9DiMmz80VmDAVOY4cFXJ8mrBqCL7blAVYkzku5eJRF8aRChTVS+Ps7irXijcp/os+vmQ==,iv:CHFdRAQ2ElLP2D1dlQsBYkjN4923pg1jTVWPYfa2az8=,tag:vsuMaedUd8KiQ1M2ZL7imw==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:v+k=,iv:roMp+U0NSy7itisWWx1wB7SvMhDPPFql+j+4Lf5vhNg=,tag:IHBatWR2sgn2CTQFxwqJsw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:UOfEDcth7A==,iv:i9/Gif/KAPRA2iFklalfbts4nj7gLNklLpAQvv+95rs=,tag:AXWKJ3vAf7kQxwRUkdk4wA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:93a4ERnXdR+ybjP7pAuiKtLgoiNhdYP49kwGWXcguCyDFMr3s9zYI6CkFbp8X1uZjxobK+o9lCHFj006mlwMvgal6FCRn0ytBs2GriXgxwU=,iv:4M6QgecRfzLF/8wICHVttR6JwEKeQHDUhwStNLXxwJo=,tag:MSUeZRAc7XuVldOtf3oriA==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:u3SbxK9xWdrBWNJztII0VPZf/iWp9vVEeA/jRLP6HvN0i7pAnZwTrsZs1cfeA1Y/o5mCTK0ibhCLh5R6e2YGT5HVxH/0Uo5HiAOXuT1jNKk=,iv:IlSZn+KKsoEQ9JlC0li0YtG3YwjHqrMDgGPUEGRRPx4=,tag:4osUMBtpGGIg249is8f8aw==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:YL9G1lGFYO6moqfm7kc2OAE=,iv:fAOb8BgXZ9pqpJymR5+bknqZvewiazBwapUQTtHSqTE=,tag:YyOSvHzc+hQaQzsko0A+qQ==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:1U7ER/DIHSCFOtiEr3R9Hld8IngUuQkLL0I5pnnJE4o=,iv:8r3WmZV4gcHY/EBMbs6uLevB8NUJ4/tHgto19tNsx3U=,tag:0YIxz7Cd4LjAWydO+D7S0w==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:y2fHgHjV977Bie92wGsaWAW4Gw1a71xcbxRi1XQqkvh+/OG5JQ==,iv:Z+PCNN6AYRjzvp+ckSinmTNMZtaPeoUOSuwY+OlGR/g=,tag:6LltezmS4Y2ye+y6Uo+Jeg==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:bAY9346QQKb6qlx/2w3VGl86Nkm1nckaGwUqS9XR8kIP+vqHAw==,iv:1w9n4rv4pXMmLEqktloHWgoAR35wAd2T9KZUXge//po=,tag:ZG/cnzkXj3FnicAjv15YRw==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:Mvdl17LlkS5wLQI13XEl,iv:/XGAzm1EY6o6z5YNPDMIwZjuk7VeC8hwie/LxF4+9Q0=,tag:dTxHyotiAbzhY0aPpoJPow==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:amfKRmj8E+qGEyg=,iv:18ZA83aJZbPGMrbuY7aIkFcSGpwtXALkkGLBNRNGn0U=,tag:IBBGBOWMEWqgSEnha/9PbQ==,type:str]
    password: ENC[AES256_GCM,data:sZF62inrOuw3gN4=,iv:wR3XG+iUNH8L1d0JwnbYXq+Zv6ksRBAmGixy0avPQ98=,tag:bpYxYTirkooTbkHREBZTCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z1VlN2lhMjNGMy9EU1or
            dnRNMlQyU3VNdTV3ZDBtU3ByUjVnNGdHWlI4Ck9Mam9tTzJaMFkwSzFNNzUzOWIr
            K0lrT0J1L1AyUjhTeFRlZzRpR1c1RUEKLS0tIGFGWXovRHU5aHBvSk1LZEVzazZn
            VEFmQTFtZjFvdHI3YXNjNmNpRnBWUGMKyUDCe2ymvYTn0Fr7BVwIR7Q7X6QaNpK9
            QvrIlxUVQxKVoNuBQKab2vfkO9RxvS+s1520+kqtJD9mwqit3x7NUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:03:11Z"
    mac: ENC[AES256_GCM,data:DJISrV0X/Rw0ummDBlRI2qDWVaaWqJVql3LQ4lyIjMX4hsnZ4dZWiNge061JwaiBS0ckBivpdTjEJoqyC9/uG9DfPinaP7CVZJJWkdSElgMMfSpcjm5uKGE+SY2n164+KRR88hhsq2KL6+P5bhKUT8HiQVtOT6wyrnV7j6NPY9s=,iv:uc+B1lMwDZ7Em7PPKHniBs/6hMYBJmsGmEOKV4QM6IQ=,tag:08F5G1ryHk1Uartf/gv6Hg==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
