secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:usM0qcjcOfcH9CJJUyyPnULg33WMgsjfC96QCnR5sSFdhQ==,iv:lALETNcWpVAlGe+WQEl8bsEM8H92a0fYk8yEE5ScNGo=,tag:/W+rDBn7Xz2Q1ZBuXrYGiA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:fM6uZDRE,iv:FP8JW0ntm0i9yq4KtKngthHWdTZIU49/Lw+/XESXjrk=,tag:c0h36nKPGKor59I1//hhpg==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:tOathXejBioz,iv:sMvAy0XT9AJKcP5jGPeFHZG+zEQA9Gnv2cQWK5iok/Q=,tag:jhP2JStSmTGbuXNqfeO/UQ==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:5j7i9/iPjtVBZjwN,iv:sP2pRnxf2VvrazvZ8WX7ifw9et/wVFgcRWQeVWp2KYI=,tag:T42dfVPd5DAmTp/sqLinFA==,type:str]
    DB_URL: ENC[AES256_GCM,data:3vY3BOOqT9BANI5vpgofayg+vcgT5992rcbbCYEDSL6wjSCnO98zGx6wT0h3fTekwjqzAA==,iv:mNfNqNV3uaJE2xE+mh+r1v3UzA1vt3oVONB8y2+Uzqs=,tag:bQLlquukQq92OnsiEMoDcA==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:6Tc=,iv:Z7FjBFQzwx0VZqd3Ua2Nlq9/gDd+Mb07APVRcsy8QY8=,tag:0HQi32Plcwxdu33L1xonRw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:OmsTMDM21g==,iv:GiUMSf3aWHXWlFMF5WANHJaJuBT1hQ72bERhXpKqQ3g=,tag:4RRat6cUKP64CjGDCWQ9kA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:E+vYIN4rSQVzJmVUI0e7UbxHw4fQqIMDhB3LCF6V8RgaAnQiOabyiSGJQ/8kmH5E9IOnWCc69v8UfRGa4iUOWvgrK1+fUYfGNkmBW4ahl5o=,iv:gBK9FN68h5k2Rs8+P/CnlygRRFJt3qb+r3YJMngQHys=,tag:hs8HggNiKSxTquyOQ4J8kg==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:7WA3Yl0v9jNBiSV1D0eHV3j/4CNttWvsqV7mpSXgvQIrMGDkX/bocQjpKTjlAmaeq+wstCq9FUvfxt35e2wOE6gnHqHIzrU/jUJPrMPJoOk=,iv:0RhZEfgm9w/BCME+0nR1QyV42ksMDEa6MHhHUIDP6E8=,tag:SLTmrPRWbCtjM7AO9tYlYg==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:Om/mhG0F+kbJnkiP4/61St0=,iv:7UltwetPmR5boLg8OMKJu92G/Ds4zf1LFBKiGA85owE=,tag:ihZiXJpp/kgQUvWMBwtC8Q==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:IeFfcw3vORwbJKCGPnSxVNAge8Uqcps73HoKKNTqToc=,iv:nM/8AxVY5c4BhZtSqOHo5kYLZ+kRhlqJjE1KPV4LmEg=,tag:/V4cjI9sN+hM+PQ3OgImyQ==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:FbucvrH+4/T4mg0YKSpWKtnlRe7ICmcC+Bk3EKU+xiJTFV6w6A==,iv:kzKZa0UGNR/0NKrqptWaWJB3Vjo2s72QqraRp8Vy8Ag=,tag:xEtmHYaHJ1CSlJz+izrcqg==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:f0E75RPHvzr9UtKjI8sgLw2n8UycM108GDcmHqOi4crlu5qL3Q==,iv:xM9yjQOdHgic9wlorzaEw3KE1ZVpZ4U+hYKdHBpYHd4=,tag:KBzz4ayJJBFyblPqFq5lGQ==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:dzeSmzhhW1B90aSYCFap,iv:F0/udQu+Vn0+E+ozlb5chnpajuBccyM4VvERlUibWTo=,tag:jQGwaW+8EUpCxwYgmAv+6A==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:+ZtoB1xysB13waA=,iv:NGvDF7t76Oz/IXEN9iOQAHxC70KmVNKZJMcXXXyVBQQ=,tag:weqrbFTC2vhYumnS5wDKlQ==,type:str]
    password: ENC[AES256_GCM,data:060KXoiwymulUNs=,iv:qVMIk9y9iHiutxbeikwH+FHp9/sdgL9PuvALv7ISySA=,tag:uM7A2kBwivDxOW3CzINsYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMng5NXJNZStSMHUrSTNO
            VVVveDRNOVBoenZkUm5OYTRGNDkzQ0hWYzBNCnNCUzZwbWI2LzI3S1RQMU5xcDhl
            UVpRK0E4WGVkdktlQWppMzFQbEoxaGsKLS0tIHhQQ0FFeGFLYU1JWU5nanAvK2lN
            b3d0VjlwL2czTEhpbXF1MnJqR05DMm8KEzEdpbl0O0RlU6FX+XhXH3U+p1oV2vVC
            BVAUFlilo93KkOq983N4lUDETDpiyfFOyKerx8TV6A/cMqvEQlvrDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:01:06Z"
    mac: ENC[AES256_GCM,data:HdeF2JrTq1VDIX/ObCiDNjelSZLxuk1DHn1z73e7EK5aG6dnASrQgw/6wwxrcKsrcE5kLyIdkJBQm5oiztnvWorrHo0/079axAIrj4nP+QuapBoCnIS6ezPPGO9wcUrOYDvQuUKX5mY3WCU3o9/e0LUCYPagQsfE7SKWbei0Zq0=,iv:hT6VtR3mMbCq6lrxOKYOVIYhmGKn/3oH+3N7Im/arv4=,tag:CYzNUEXK6MsliNQoZkfqOg==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
