secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:RRi8fsBjpSJrVbPDgtKAjs8BoUcp+urRTG8iGE3nWXvKwQ==,iv:+7Cp4TDOq9LhvrEcnbkQRJHWAoD8Bo0xdwl4qi48+sA=,tag:zQMr6cwPyVJWa9DrLATtsw==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:ODCZpK2E,iv:8iq4MFU7EamVB+UeYMm9ygx/jrpUmM5HTwRRXMBqWf8=,tag:QIWqyZzU266nBz6yhpxXNg==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:dQq8QE8hTH34,iv:r/2oK5C7XceyQNBPJjeL317TWAVx6tV6jWziUwUiCd4=,tag:74nO8K5OYD0S/UQA1hyEfA==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:Jxww65idJ6fhHZLB,iv:A9U0h2F8euOhGGNNWmaE7UNdcd8skr7Mz6vBM+ilbQA=,tag:7VhBWNBe4r4hlt4a4iOPXg==,type:str]
    DB_URL: ENC[AES256_GCM,data:KulM9SN4LvTEGv5eUoLdc9pKvnXnfZw1VzckfqUDYCuxgIdq9bfIW82Dt1i/kwvb4BymMg==,iv:JUxko0PuWUmH42zXczlBPk9YUKlbcEJLD1uYoxi1yEc=,tag:/SWXWKR/Ppd2Be5x5K1ltg==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:9Fs=,iv:y4352Rp7/Qljnxs7yq7rwFiS12Ou6VwKhVtJ7kAInLY=,tag:+LcmUilOMaYEQosB9hlWrw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:PAqamtf3jw==,iv:amA4DBnw8tt16I7dvKU4TVpOeCb4XN0cnk8LPCp3gEg=,tag:cUQYXK/pC/FGkxmhCpQgzg==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:qQc83cudzSNm+sm454m+4Hq0E2Ss1JH9398ekBOrA2ZM90eFMNA52rlNlacFeygJDJj1AaCz/49OkCFTvlc7xuZkYh9hI0SHnvDwaPCseJ0=,iv:RiY2InRQdGi5QkTXASo0cOX8y20HbSt+9PLQsQA5CEs=,tag:210mn2ECFWED1v3KwDI9wQ==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:TwgW9sjbpc2XSb2zV39ifbcEgPeCEBPBnQUmBj6Pr50KdtoMi0Hi70vsJsIbkg4d5CyPHMW0CZY4NUkJB8a/dMfcCCup0Dahx7ThW0RAZR8=,iv:HHVoAKD/F12o18qOj6p/96QHVMlG/OkzUC0Nj/Kboy4=,tag:MN57/Rjv+oERs3oV8j3JLg==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:B4g+Dbr6jZkrKV4G9OxMA28=,iv:dwm95weJDBOeLgei5PsfWAeCO8pIs0XVIFc31cDhyOg=,tag:y0GwFZN/Sr01RbrB4HKWFA==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:ydre68ZM/wA/sFBCguJpcezbS7zs+lpnNb62iMo48JE=,iv:kYrV2D+d5J12HDi2DLe2JInPm+eCXdLEdcqEdvUysAA=,tag:Pdw1n/cAEOl2Whj7OFk8xA==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:oCcyScfbuLyrGRh1FK/wz913xZ6LPxovZR0d5OYZZypFsJtEkQ==,iv:L7uItHz42UaPnzX5Ij1eYR/GgsqiwySTuf7yMrwam94=,tag:agqI0lfuJl4z2jJFLJWumw==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:V3VS6SVqHgwO2MuZIIVV1Epa1z0JhXNP6wlv8xSQCOE/mc68mQ==,iv:Qdm0hjrOnLE5PVBodmEhqGt/ZyiEjB1plkiLDOIlnHw=,tag:KlDK1nMqMS7t36rVZl+7tA==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:ZtK161MBSHZ83feMPxQM,iv:pnqaoZf1LZzQPUfIyH37wScVkuK7g3k8bULqMe/OoD4=,tag:SkwlH/Wn9qXyLVGHEesMFg==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:cJ7vV6w2frGedk0=,iv:lP38a4YU9gf8iiLqhTSM87AuTT0blq3wEqHpddoQFS4=,tag:F6qn4lf+rfxXysj7yzOu8g==,type:str]
    password: ENC[AES256_GCM,data:fxQyHt4ZYXCOYL0=,iv:L+yZ8rHBBTq1Gj5ROZMQICfqPJ4MvGZm1MCUhN04Xmk=,tag:15h+Zx4iK5F4s2H+7No/GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdnlkeVFwb0ZZbitHVEhM
            TGZXUEVBVktJeUVEdXhCc1F3TFczSUpUWDNFCnpVdUhTcDd0bUZMK3VXbUkrME1X
            MzNNTTB5UXNhZVdwSEpMdDRuaWhXVmsKLS0tIFZDcFV3aUJFWU1kR0JWSUcxZ0Vy
            d0tGOWRZS1lrNnFHQ0hOa0ZmZzhNcHMK7Hts6iVxzziDg92yfxakJcO8z192vDt5
            vhlMRpubebmhdWotsJaT+b2AWKvE9Mrt+87hC/66DXz8SgBh8jO2xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:38:13Z"
    mac: ENC[AES256_GCM,data:a+DqAK6urf4yBiA/WjbDDCONXI4LLVL+Ut0i7y68js52jXWbxKRozbf0JlGVcSyrbvTUgAuceKqWKEm+NW7o33eyS3Dv/u/PJCDtzTzvJsjIvt03MU2315FWwa/X0WfqpnXgirdaasUv/Eky18HKj6U8qLI7Z8HMPW5YuHTSdeE=,iv:C/u2CbLKmnBflRIFYHiLU8yx9naxpuQgBSu4nreHVDU=,tag:Q4fCwShmpwjubPizAabbPw==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
