secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:RM3f245aZNwxmEtB9nqrv/aE4Y6N/uJxKk6ANcwMWmw5mw==,iv:5WcMbPjvLjFHaGDyQHE95aRZkTkfl6oIYI+9cpa8U4o=,tag:p3BC62isRvlpdp2L6b1mAA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:XkXI3Rjg,iv:BBWcdHB9gxJvdanaQ0onj5r/y5G4UihwjaUsTH0vIc0=,tag:deLrRLvHFX/kXpJfEJaVTA==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:CpoQmOnzHqQE,iv:SkyHjL2K+CfUARBz3UnkphQeV1bhdAf4xZH3zhMPLX8=,tag:aTOkJEjiNkTdGL7rBBrVag==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:2+t731LIN6kCYFFJ,iv:8HIUBUksKUK06ntrAafoHrntfEywImthFrWBGVpZpGE=,tag:aWflow+fU8rSt7vduouJNw==,type:str]
    DB_URL: ENC[AES256_GCM,data:VTskfKoUjSuy93o07c+wKgD+aznlC/TobF1DBboYNQKyKEJd+IPtBthCeLDWutUAyALEFw==,iv:7XjjM+U/cwAOtIV2x5AJVTkdhvkQkX8s9mU42NBl+70=,tag:R2d1gAfNbI4zG7GcrWxgrQ==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:Ddo=,iv:r1nuRWWNu645ds0kWaMDUQR7CSbl1KknCe3n1PWbyZ8=,tag:nnHcwe7N0se1Ji5+Uxb3wQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:GEkFfQp4ZQ==,iv:RI7J6Jg7RZAh1g3BuybjD2ABMwLBe8B7TqEiTYwFTOM=,tag:iITb5wT2+lIL+q0FdniJTA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:eO/CYu8UTEiGBG7emHSr+84fN6rlt6G3Dbo85zmf75rDh+6KHOj8O7O4BD4CjJDeLR1NUZ41XgZ5rGX/ay5oH+JSUP8KXPBP7w1/Zt3skf8=,iv:zWIysEXFQCgk28dQg6eKr7lxHWbgt4MtS9YlU4oGzlY=,tag:TA50Nw79U9BMBolCxTSBhg==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:afCplxbMcISNsm/wq+IW84fSK/pxrnnKcuHWRPDDSfr0qFNJrpKJ8fk4Bhprf9IHbRd67tcQeo42ueHbnNWlduYBZ/2feEHUPsmrS3IY2f0=,iv:661J1rzagFoQVS31fW1FZZQSYt/uMFjlaVfL+wXeTLg=,tag:Mx4ZTs9JmZE7hdb4GHlhSw==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:OO+q5RopVvkC2nWCrBYoPJs=,iv:7IrvZtkniFRKCBoFeSV49KETjVxrb2G1wWy431Ew6dw=,tag:uFYNymL7Vp7zzGZC7n8aaA==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:esrMoCyae2S6NlWtcPvx3FBO/ShtSgipzy12sXEpUiM=,iv:0tuMJLeETwno5pLkt9RlBByhYhXBlWYkN9K6OJgT1lk=,tag:fLpv8yMHEBQ2xfaa6r+NHg==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:Gk0LS6c1W53QqPEtMAwmonNq3LPQkLst1ajrgwbRmO/dFz75LQ==,iv:0ipbWK7FnuVIcS+hP2FKDemmUg/qzCfhLhHzNLJBabE=,tag:YoeUDQPBOBFbSoFzH1094A==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:awQqKIlGZANiifG7/84qnUew3WE7n+oxcgvR+N+b5jhvd277Nw==,iv:KEIiFF9ga0PtSfD3o2Q6k5siQGQmgrKbvOEGB8pHCYw=,tag:psxtPQM7GGnBFHo3AnP59Q==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:RRgp5I9EORcBsYEOg4kU,iv:uwHudAXkw+p0ueBrGoNipXYUIcYxpTPlRDapzk+irAI=,tag:ZphXDrJBB7CrFM3cxBOt2A==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:X5n0/ug98Lgl8ts=,iv:UZ5WvgFW1SSSshvzj77caWWV0nkZrA0J9aXYkpawOxg=,tag:D1QpsNuTg0MP+v0Ht5/Jjg==,type:str]
    password: ENC[AES256_GCM,data:TwRFV9TSNQGSdPE=,iv:P9/LPajkhGJuUh3QqRlcppQeJAqth8ADzsDV5Ffh8Ug=,tag:rBsPzBpzRh/DCcHtGZlJHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1JvZC9BOVRLUjZCemto
            c2kvb0FFaEJ1R3c5YWdxYTZ4bGNaOFk2b1M4Clp1cU1KbUp2OU9aOVdhMjl2aThv
            KzUwL0s5bU1QZGF0Rk5PaUxyaVZ2MmsKLS0tIDJqUFMwQjRRa1daNlY0bHBFTU5w
            MmFBTjA5UkNlTXdOdHBpVFFvK1F6WU0KNGGeI6u23nImWQ6qnjzDBifXv+abxqs8
            6G9z5GyKFaSMJtTRvcqscy5IAcnwCnx9X7eFRn9JFpXO42Dweat4VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:49:04Z"
    mac: ENC[AES256_GCM,data:uWxH/UQZiXcB0ogf7dZ86yLuHZd9qdYu8X6VnUMy72eXD7UZa+n/f1s8YDXZnTNR3kaytsL0XvXTJSV7nPqU1pmdY+Dlh92f+rsJ/MybDWGQs1Xg0HfY5R5CNLAHUPCf55ZnguES4t8tWznIryPehu1Q4ZX1Uj6SVhqzQ/I3oVc=,iv:Wd8mvmdClltE2Q/WXIaoOrgEOwEu81VFwP6g0OkIb50=,tag:9rUXehEbJkhZSVeLUPz5sA==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
