secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:3Ul0HiY0VU9ZlK1gaoO5pAXDtxpApvfYPlaOAM9kWGQS/w==,iv:7WuhdJ/X0rzZ6WSutKbZZ9MQ7XTDoCYJEa5Gq5N4UZQ=,tag:xx2KTSd+FpSUF+ItGvHudg==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:wBMbqyb0,iv:tR58Q+3hctndDLtdQRg7edZjj6S69iCAPh3uzmLEnvc=,tag:K2so7wOozB6HvfF2xkv1KA==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:U3gbPGues7BY,iv:l8cSKBaUjTUKm5eBQ4Adtdtz5Ir4oDboByygYyPh8nQ=,tag:FLFxWLaPXSjez3JzKqVnew==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:B3a/waOF22jA06gd,iv:qr5jeqWO+C3a7uf7bGblMF5cQ5jgL1KJP2hEqdoD5ro=,tag:ciV5sNAL1hz6/W0dzUggNQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:UE6iQ0mfIx6rHjk53DVm7c7hSn1W1MbE+dgaIhYhXGSj6HlguLe3aV7RozG5ddFscevvww==,iv:waxB0YhQEqCpuXd7A1YW0GIn94jMh3eBcC+e1WAY4dA=,tag:4cnoRNfHgJKYDzt2cZ+Tww==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:Akc=,iv:8gzm0AWCyqZ+/WrcKq5F3/n+j7tsYdveV0DFddgXrg8=,tag:ndmGfN99bDwjSRkOlo6bwA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:TXfVSI0i+A==,iv:PVJMRL323VzNqi3JE8MMOjIlkTdVdLQmMsB2DXPPcDc=,tag:iM00/ulV5n/wKlHCG8UChA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:11gwYDOtwov2+tVQ6qhW3WFZYfyBHAon9gYsqk8l92fDpX5LrXuC7jKTYZaCMB+m5WFM6QB7g+Q6BNSqvxmj6MRG21/FuEY6kcsPZv1FP6o=,iv:yMbzt1Z4QmRWnmrFxgUh/yQ6e4bOZh4M38owuyrF+DQ=,tag:FJwP4BZUiy9p9Sb8K283ww==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:+XWQJnkg8ZND8BVR6cvooOTF3YAYspYzGkcIh2HzcNkHd8K00mry1Xg9Bi0xLXHQPdsYUUhdzAagCUljGXtjf8YqeeFh/AY3f2wmKFAQjC8=,iv:vRXum5vUUu4N1VQ2ZrD5pGq0tq231hyujF9rl0KGkRA=,tag:RZ9om1TsPrnPdgF1EMjv2Q==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:StCobN4ywj7oNzpeZjyeMVA=,iv:mYmni4EelangShfAEI3yzkPUAA2xc5qKDCBpXUSI/oU=,tag:lhm6Fu9fl3dIyA2nIP1bDA==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:FCphQOkU9tAPSzdI1gNCHLMfBvPnCEEJApfS74AfuNI=,iv:sLO8kYOL5JRW+Zfmy467I4ZCKlYCCfMX09XSv0xXkAY=,tag:3WwtFjy0jSc1F7KeCye/bw==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:LZzyVtlF1RKJaw0PMrXMcL2gdYIUKyzy4pYmhT7HTjAlxzTISg==,iv:WmUzFyTprhMW/MsTxRRU8VuAq2PGHKgBUcfqVm1Z8mY=,tag:jyCPgsfjPQWN+9ryiOQ9kQ==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:aWx8FEYTgi3l+VNBFw+KP6P6mg82HNoolCEQQRfSGxRhW46PAg==,iv:26xri4HqcewZK2BfQUVsu2fZbSCtgZVdgmTMK69x0n4=,tag:ACWxlxMrEW2pldGAdDMraw==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:Br074jQf3JOlIcwfa6yH,iv:zGnka68p4cLDDInaPSugkrRV4JzqPaggDrYE/VxY6TQ=,tag:1RRyvDnvmku6uQGil19SIg==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:5v3PrrScxaJuARY=,iv:6cFG2/0bNoBq8EdGCfOCQEDkHqyzdqDDmbFIgiRIFtI=,tag:0aB+wN0NK3C5r2ttPiFGBA==,type:str]
    password: ENC[AES256_GCM,data:TOa5thmTXRvF2P8=,iv:H5QgIkzmm1lNXQIjSvcPDyvKyRylTfo5wlZcrPIVTs4=,tag:FRETsXQvxID6EKC3xbouEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb3pORm5YUS8zNGl6REQz
            ZUlqaFZoWW45YStEWGMrTnNRWUhOOWM3R3pJCnN3dnptV0Fmb2xyRkxYbFNJZmFt
            cE5mdE9lOEU3U0FwZ3FmMlBaUDZlZkEKLS0tIHhRVHJ1STBrRHd1UWw5RmZyYk1I
            bmtWTWNaRmJFT3Z6UlJJbHdDUThtMW8KmJVF74KupS/VE8bV26l/Y7PlEjCLVa64
            o1cBgi3l85Ulww4R4fPKV12sMtaEK+Rh8mYgSRPgOsTriS51j6Va5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:59:10Z"
    mac: ENC[AES256_GCM,data:2fYS7+shFZOjuXK7S8N+eHLWswDGABAV+N0xdZpGzpSL9ONij4yGK/gWAkpq5zdvQ6t1f9HbUsQjXnFExWc5SZTyDxDBOq6W5jBv3JqASEcAt3eTnP6J++L1w1hS6T3E1+6a70pPPkI1dOR2Cm/8NvIYfuJSNFsi7tIJogMLl30=,iv:EGo3/wk9j3DLSzgC0ImMvh6g/hGiKpNCU90DkcAomWI=,tag:QyO2GU1QNrtb5b7ep3iD4A==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
