secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:pwynOopNKca1nX8NnTBubovKAGlYnFPmjlWnpjnl9ah9aQ==,iv:mCX/DgzTkqgKNznm4c0NurFCCG0PqOmQY8Y/Bn7G9z0=,tag:6tv0aT2rULmaGK6WUtKknA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:3l6c5YiD,iv:fawrEVTuL1Aboy17pIY2JeRQe/PgwA/Fp/8MaZJdvjs=,tag:YU2fgYWr0W4lsRtFGJyD6A==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:neHthOdg4TBo,iv:6W8iAk7Bq/QrYZ/6GQk4EnmyRQ/+JV3BdIipQK8AKL4=,tag:Qo00saZTKC4Y8HqPwSsjSw==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:/PmqZ1LwondIt3FF,iv:yNOG7R+3MImSGc1pF1FOXjxqd6EdGiAOu7JnB4e1cNQ=,tag:8T9PY3F2ObXXpiiz3b6OPg==,type:str]
    DB_URL: ENC[AES256_GCM,data:MYXELa3/kVby6iIhDp9yl0fDIIiP+4CJ71xv+o153ToHEoD5ncM8zkKbUd9c/N/Axfz5kw==,iv:t3gWycdYePDDJH7RjDR0Mj3/1mFkMKzD4YUPbxDxRZU=,tag:/UPFLg87ddoF2prkn7pE9w==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:LFE=,iv:zYJxQj05uilK6wO4jrgk4CXowhPNWh2jjBn1gnr7PyQ=,tag:CEnoXlWHGD5mSom0OmUZqg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:/VDigDNlsQ==,iv:G4dszn4iEL2Pb5/uHIYoslqIzCJdgVjdZ13+TQmnTQA=,tag:hcaSMjRJx7REj/H6/7EJxA==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:Eg87OqO1nKJy0a7/Xejt32Vpd5Y6PAvg/EVxsi5fla16Lxdo59wAV0BxqTvUjJGCPD0KwNPqqN4TkzfCh+rpDj94FKPOCd28zB6EhgK1MYE=,iv:OMa2rmXLQPJ6SRKr3iZ0iW8vLMOzOQ8CDomyFE7c9fI=,tag:mVwQr8mAOIa/autGpg9B8Q==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:cc3RQmW/UWsSsFNR4lRYGJ4DdoDyaRW4f6yUbsl7D7cJy7ZtstdE8agAizbLK8wEEbZk+P2pE95ZjEKb/mhcxtHPM9Z7+YdisJ1fGozvpxs=,iv:QWljlFPX8u0foVF7B/pQh0HxEGnJSxvwqHv1FRcnG8A=,tag:OqqnWvOWxSq47x2oUri11g==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:TiIf0GAtVqQpDmM8XNbpU3Q=,iv:BH2vHbO0GaX+fW+LYH2JAHZRmvu08W8W+NJjcQ8fjNs=,tag:xPjqDSdobVz9f5MeIqo6cQ==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:06RJlUe7BqGGi1QBFqLJe/iTGHaGy69akFf2sxvtZ80=,iv:qU8PMvf+TebfGkqBw6fWIwUmomyXPW8OvdBWcnmNoW4=,tag:0pslZzTJCTs0nHmvWm1M8A==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:5GUgX6z9rzVDvO02jdcorbf863wxWMbCtjaa5zkjKeOYHZGedA==,iv:riQdy1O3blSQfJJCCXW+TWrbnkTfAt0HutqL5vvuTBE=,tag:jQybq1Citne4wbJgXTqGOw==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:pETDcXsHmTwkdhIZKJ1i4eRNraNRhTuT6/LAadDw1Hl8V5Gluw==,iv:aUMFx/JXuW5CQTlpXqQBrO94T1V5+NcQJPmqU2Uoxqs=,tag:Ksg/yZ1Fsa+twthrkghr5g==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:eio2jd15wYQ9ASmOMJku,iv:+NNthJ2ivc6pmvoIM3YtLECFz5oeC2G1EbOzxVUWocs=,tag:/4fDO9XV7/Ri/I+q9pfLqg==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:C6QGz/mY9+5gMvI=,iv:4X+81KLTQ32e17VoiGWKxwZlc7681Hu7P9jlfxkkOFM=,tag:ZUt+YTPtsNU4jcR1oCle3Q==,type:str]
    password: ENC[AES256_GCM,data:QEGrvy0sTuTfhA8=,iv:OS6JP9sa/BG8zBHEvcbEHMoU5R4MUqxDMTDgkCvh6oE=,tag:hMl7/KKng4K9cwkN33XhUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOWlBOXlidnpzaVExNGZl
            ZE14VTJDQkptNFNqMmVKTXBhbDVjbVNDdm1RCm5BRDNqQmJiY2VtMnppSmhRaEx6
            dThLQVkrYklkTFhqWVo1VGV2eUUxZWsKLS0tIFk0MTlqT3B3UHdBNVlJQXFkb0FM
            aHdkU09pQXpUdTRSL0cyb01jS2ZpeW8K2rpSbG2Z4QxplZNMdNI6chHfEtCreu+/
            3By1MRPodQ9/4ovsLMkSuSD9FhostDtPiuSBSEgufQXKrXy6fY6Blg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:36:59Z"
    mac: ENC[AES256_GCM,data:5lwvEIqqhrDW9gPQUXaV3emtKqukprXjs4C/Aa6Ks/BYT3rl75aFeqz48nX9UPfdle2jgkb9dNb/2as4T1Fa2syuCS0vyybrtjy1Re8cL7pvovNbf9edARYVYyuKhd3znxe8O7y8tqW0PoVoSEtADcpBPtF/A83YYWhRlPxesD0=,iv:PRiUfPXqYpX70yLo9m6B790GjmkAaH7a5SW8cmL2x10=,tag:ihNtcRNfqmFBTE3HPxGfFQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
