secretData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:aJ95EGZvZ4nk5QicoaPRvt7jznD3K1HZN/ANzVoLszj0NQ==,iv:6B2owVROZCkSp6BO83a5lCK2HEp1ftpQVpYNPKPpJnM=,tag:6GiLCkySkcgkr7l8+y9THA==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:LoYD+hKl,iv:36OYBe2CQHi8JD2bzxXE1jWSJG3cYfxGUS5T31XXtfI=,tag:F0Wl4js9Pkh6N4pdPJ2HUg==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:cPIbwqCdmZ4m,iv:yUIWba6UmZ1mYzNgqmUlGEdWZOPEC4QW5aeOhBT14VU=,tag:s58DrNTPGjbBh5QaHiuGow==,type:str]
    AMQP_HOST: ENC[AES256_GCM,data:HEifeek98Pt+l8Un,iv:hNtS9DFMHGJMd4BtquwtFqhxAhYHFoJ4YiB8jkS1gbU=,tag:uH2VYooW1Ghr8Gp7l2XdqA==,type:str]
    DB_URL: ENC[AES256_GCM,data:lhHltan5U7gyLNIB0Y7OSBlQ3wBMFNydt0zQCQ3cIn8NxkFLTBPbNPGJXI8u7atgRayCiw==,iv:MEvWlrc7qaeAOFRbyIhJRoNlfxllVtf8+SYnOmzIIN4=,tag:WoTyNKrYG9yL3eURhnzOVg==,type:str]
    DB_USER_NAME: ENC[AES256_GCM,data:HbM=,iv:8KQoSaPU1l5JqC/nNGeDZeZnVPGt6i5LbU3eIypOt24=,tag:+rZM0EualNccxY59HGrNvA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:FXowovVtdg==,iv:Eq8+XXZR6xZAJQgEjU86OrxtVtozQhnXDNDH5vxAea8=,tag:Ptu2NNcZCfsQO/J9WjieGQ==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:dhsjUJlgdiv8jwO5xwEuO8hYGLtqooMfjCE4WJA+e1Ch7Gg88KgR4nUbrp/Hm9F85kaKpx2bp70DrN4B63eL8eDSymM+VYYDfCnFoCdQHJk=,iv:SHP2bNd8cxAHvQ49Eku67+TcILWtpgdq2VOo7ptnZDo=,tag:S8rv/KMADL4PhA88P1piMg==,type:str]
    PAYPAL_SECRET_ID: ENC[AES256_GCM,data:R3YeiQC0pq1tkYYIjxQwKwjPTFX1hasapfU7kJiP9gURKFAeDdIxvI80QiQb68HZbrdVLIyt03MHALlIhSX80qAHWl3aqAPj6TO+on4v67E=,iv:7Pvf5M6t1tT7g6gotzgz1acDnPg5th14ic/ABYHANbc=,tag:pVOWQrneG4T5mc4k3ojJWA==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:sJsa7xdjsInIMyrGFMjd7tc=,iv:YUOnr0zhXFKvLjo5qdn/WvK6697xo+PYQx4gKxhor3A=,tag:TS8hBiq5RYrdh3fGqM+Fag==,type:str]
    PAYPAL_BASE_URL: ENC[AES256_GCM,data:eUIUsMlqESsvb21Um1+UE/FB8snCcFz1MHvB+VDk8dM=,iv:874Gi3akLsSjSB5QSwoDLtgtBctZtT+zD5JwEyv/7LY=,tag:lhLon/ykaPBmWzViDWgchA==,type:str]
    PAYPAL_EMAIL_BUSINESS: ENC[AES256_GCM,data:ZTXQOmDLhAbcWPG67c+rdkT6rdPg24rXJRqa4do/7wqK18tDAQ==,iv:29z5UpGkNjPLtxQuO9Tw2hPfVqr3Sn7oU+rl84t+Hvk=,tag:cUi97R88LWIHiMckBcLC1Q==,type:str]
    MAIL_FROM_SMTP: ENC[AES256_GCM,data:QZwA94SiSpMxm+57Uk+oIy0kSnB64Soq+hdYCfdCqz8kZ/CE5g==,iv:awl6mE5Rl0EbX7au2qe+h6Wjd8G6kpxQx0HMzabIIW8=,tag:OV38IKQzE0L9Tl6y207EkA==,type:str]
    MAIL_PASSWORD_SMTP: ENC[AES256_GCM,data:zjSyjEeqicLA0ecKPRnJ,iv:hmeujI/K2vuu1qCj0ZHXhn81nVVyKiQzbRUV7vtdFDg=,tag:JQZi0M3r7pNLqgXLdBSEDQ==,type:str]
imagePullSecrets:
    create: true
    enabled: true
    name: nexus-registry
    registry: https://registry.llince.com
    username: ENC[AES256_GCM,data:z27+0ipYEedO45Q=,iv:ZPVMppDh7igsoPpcU5AGRZa/5ZTcls1lOIQ0psOTHUM=,tag:YdqXiOpSG0Cr0LIyyBVUUQ==,type:str]
    password: ENC[AES256_GCM,data:Viqzr3XapgijJ+o=,iv:fCk45OmERp8ZW8rO8mFyHQsID987vQVWPNrcBX8X+fU=,tag:7qq6KYOOjjhRLY9T0cS4sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age137jp70m9dztshq3gy8r9yfyzpay0mv9qamkyjfstrrpg42yjzfnqy7wka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwK2RidjZOZnFYMG1aNkhH
            ditKYlc3NDdRaHduVWM2cGtjQlI1RG9CWVJrCmllVnpuNEJPSXlidHJsNlZZalBJ
            QUluSFdqR0EvZjhzbEU5VkFQMEM2STAKLS0tIENuWlBNU1NHKzBSR3VreG43eGdn
            OUJQOHJNRW1UaDMyM0d0YnMrZHhCR0UKPs+G+8md7REDZ/uSBnz56usmc3gqSYSI
            sSV18J2jmClhv51wh7dCeRtQLVmsyWh2glxP3rRgGSo8nBaTaP9uZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:51:04Z"
    mac: ENC[AES256_GCM,data:y+Abw58kL8yqQBnb+pAmFVbtYvmvu/04+0/Bb5dIYpFp9418PMvMk15Bzdj5OnV2VIAuPw9nuW7fMmtmS/h/lJXUpogdw6NxNgPoylRFl+S37vdHSLed9g1Y26BBTyc0gOGy01zS3j31bXyGxUUeTrC8dYAsCcfhniwJrBWLhi4=,iv:d6KfAJuoNHFl5YYR1cib5jMOyhzbzNRMqCQeivP0pFs=,tag:7P/wytSKJ94+4SvGBbap1A==,type:str]
    pgp: []
    encrypted_regex: ^(secretData.*|username|password)$
    version: 3.8.1
